/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

module lfsr_4bit(clk, reset, q);
  input clk;
  wire clk;
  input reset;
  wire reset;
  output [3:0] q;
  wire [3:0] q;
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  INV_X1 _09_ (
    .A(reset),
    .ZN(_01_)
  );
  XOR2_X1 _10_ (
    .A(q[3]),
    .B(q[2]),
    .Z(_00_[0])
  );
  INV_X1 _11_ (
    .A(reset),
    .ZN(_02_)
  );
  INV_X1 _12_ (
    .A(reset),
    .ZN(_03_)
  );
  INV_X1 _13_ (
    .A(reset),
    .ZN(_04_)
  );
  DFFS_X1 _14_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(q[0]),
    .QN(_06_),
    .SN(_03_)
  );
  DFFR_X1 _15_ (
    .CK(clk),
    .D(q[0]),
    .Q(q[1]),
    .QN(_07_),
    .RN(_02_)
  );
  DFFR_X1 _16_ (
    .CK(clk),
    .D(q[1]),
    .Q(q[2]),
    .QN(_08_),
    .RN(_01_)
  );
  DFFR_X1 _17_ (
    .CK(clk),
    .D(q[2]),
    .Q(q[3]),
    .QN(_05_),
    .RN(_04_)
  );
  assign _00_[3:1] = q[2:0];
endmodule
