/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* top =  1  *)
(* src = "johnson_counter.v:2.1-15.10" *)
module johnson_counter(clk, reset, q);
  (* src = "johnson_counter.v:3.17-3.20" *)
  input clk;
  wire clk;
  (* src = "johnson_counter.v:4.17-4.22" *)
  input reset;
  wire reset;
  (* src = "johnson_counter.v:5.22-5.23" *)
  output [3:0] q;
  reg [3:0] q;
  (* src = "johnson_counter.v:8.1-13.4" *)
  wire [3:0] _0_;
  assign _0_[0] = ~ (* src = "johnson_counter.v:12.23-12.28" *) q[3];
  (* src = "johnson_counter.v:8.1-13.4" *)
  always @(posedge clk, posedge reset)
    if (reset) q <= 4'h1;
    else q <= { q[2:0], _0_[0] };
  assign _0_[3:1] = q[2:0];
endmodule
