/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

module counter(clk, reset, up_down, count);
  input clk;
  wire clk;
  input reset;
  wire reset;
  input up_down;
  wire up_down;
  output [3:0] count;
  wire [3:0] count;
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire [31:0] _16_;
  wire [31:0] _17_;
  INV_X1 _18_ (
    .A(count[2]),
    .ZN(_05_)
  );
  INV_X1 _19_ (
    .A(_17_[2]),
    .ZN(_06_)
  );
  INV_X1 _20_ (
    .A(reset),
    .ZN(_01_)
  );
  NAND3_X1 _21_ (
    .A1(count[0]),
    .A2(count[2]),
    .A3(count[1]),
    .ZN(_07_)
  );
  AOI21_X1 _22_ (
    .A(count[2]),
    .B1(count[1]),
    .B2(count[0]),
    .ZN(_08_)
  );
  AOI21_X1 _23_ (
    .A(count[1]),
    .B1(count[0]),
    .B2(_17_[1]),
    .ZN(_09_)
  );
  XNOR2_X1 _24_ (
    .A(_06_),
    .B(_09_),
    .ZN(_10_)
  );
  NAND2_X1 _25_ (
    .A1(up_down),
    .A2(_07_),
    .ZN(_11_)
  );
  OAI22_X1 _26_ (
    .A1(up_down),
    .A2(_10_),
    .B1(_11_),
    .B2(_08_),
    .ZN(_00_[2])
  );
  MUX2_X1 _27_ (
    .A(_17_[1]),
    .B(count[1]),
    .S(up_down),
    .Z(_12_)
  );
  XOR2_X1 _28_ (
    .A(count[0]),
    .B(_12_),
    .Z(_00_[1])
  );
  XNOR2_X1 _29_ (
    .A(count[3]),
    .B(_07_),
    .ZN(_13_)
  );
  OAI21_X1 _30_ (
    .A(_05_),
    .B1(_06_),
    .B2(_09_),
    .ZN(_14_)
  );
  XOR2_X1 _31_ (
    .A(_17_[3]),
    .B(_14_),
    .Z(_15_)
  );
  MUX2_X1 _32_ (
    .A(_15_),
    .B(_13_),
    .S(up_down),
    .Z(_00_[3])
  );
  INV_X1 _33_ (
    .A(reset),
    .ZN(_02_)
  );
  INV_X1 _34_ (
    .A(reset),
    .ZN(_03_)
  );
  INV_X1 _35_ (
    .A(reset),
    .ZN(_04_)
  );
  DFFR_X1 _36_ (
    .CK(clk),
    .D(_16_[0]),
    .Q(count[0]),
    .QN(_16_[0]),
    .RN(_03_)
  );
  DFFR_X1 _37_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(count[1]),
    .QN(_17_[1]),
    .RN(_02_)
  );
  DFFR_X1 _38_ (
    .CK(clk),
    .D(_00_[2]),
    .Q(count[2]),
    .QN(_17_[2]),
    .RN(_01_)
  );
  DFFR_X1 _39_ (
    .CK(clk),
    .D(_00_[3]),
    .Q(count[3]),
    .QN(_17_[3]),
    .RN(_04_)
  );
  assign { _17_[31:4], _17_[0] } = { 28'hfffffff, count[0] };
  assign _16_[31:1] = { 28'h0000000, count[3:1] };
  assign _00_[0] = _16_[0];
endmodule
