/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "single_port_ram.v:3.1-26.10" *)
module single_port_ram(clk, we, addr, data_in, data_out);
  (* src = "single_port_ram.v:8.38-8.41" *)
  input clk;
  wire clk;
  (* src = "single_port_ram.v:9.38-9.40" *)
  input we;
  wire we;
  (* src = "single_port_ram.v:10.38-10.42" *)
  input [3:0] addr;
  wire [3:0] addr;
  (* src = "single_port_ram.v:11.38-11.45" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "single_port_ram.v:12.38-12.46" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "single_port_ram.v:18.5-24.8" *)
  wire [3:0] _000_;
  (* src = "single_port_ram.v:18.5-24.8" *)
  wire [7:0] _001_;
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire [7:0] _031_;
  wire [7:0] _032_;
  wire [7:0] _033_;
  wire [7:0] _034_;
  wire [7:0] _035_;
  wire [7:0] _036_;
  wire [7:0] _037_;
  wire [7:0] _038_;
  wire [7:0] _039_;
  wire [7:0] _040_;
  wire [7:0] _041_;
  wire [7:0] _042_;
  wire [7:0] _043_;
  wire [7:0] _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  reg [7:0] \mem[0] ;
  reg [7:0] \mem[10] ;
  reg [7:0] \mem[11] ;
  reg [7:0] \mem[12] ;
  reg [7:0] \mem[13] ;
  reg [7:0] \mem[14] ;
  reg [7:0] \mem[15] ;
  reg [7:0] \mem[1] ;
  reg [7:0] \mem[2] ;
  reg [7:0] \mem[3] ;
  reg [7:0] \mem[4] ;
  reg [7:0] \mem[5] ;
  reg [7:0] \mem[6] ;
  reg [7:0] \mem[7] ;
  reg [7:0] \mem[8] ;
  reg [7:0] \mem[9] ;
  always @(posedge clk)
    if (_051_) \mem[15] [0] <= _001_[0];
  always @(posedge clk)
    if (_051_) \mem[15] [1] <= _001_[1];
  always @(posedge clk)
    if (_051_) \mem[15] [2] <= _001_[2];
  always @(posedge clk)
    if (_051_) \mem[15] [3] <= _001_[3];
  always @(posedge clk)
    if (_051_) \mem[15] [4] <= _001_[4];
  always @(posedge clk)
    if (_051_) \mem[15] [5] <= _001_[5];
  always @(posedge clk)
    if (_051_) \mem[15] [6] <= _001_[6];
  always @(posedge clk)
    if (_051_) \mem[15] [7] <= _001_[7];
  always @(posedge clk)
    if (_050_) \mem[14] [0] <= _001_[0];
  always @(posedge clk)
    if (_050_) \mem[14] [1] <= _001_[1];
  always @(posedge clk)
    if (_050_) \mem[14] [2] <= _001_[2];
  always @(posedge clk)
    if (_050_) \mem[14] [3] <= _001_[3];
  always @(posedge clk)
    if (_050_) \mem[14] [4] <= _001_[4];
  always @(posedge clk)
    if (_050_) \mem[14] [5] <= _001_[5];
  always @(posedge clk)
    if (_050_) \mem[14] [6] <= _001_[6];
  always @(posedge clk)
    if (_050_) \mem[14] [7] <= _001_[7];
  always @(posedge clk)
    if (_049_) \mem[13] [0] <= _001_[0];
  always @(posedge clk)
    if (_049_) \mem[13] [1] <= _001_[1];
  always @(posedge clk)
    if (_049_) \mem[13] [2] <= _001_[2];
  always @(posedge clk)
    if (_049_) \mem[13] [3] <= _001_[3];
  always @(posedge clk)
    if (_049_) \mem[13] [4] <= _001_[4];
  always @(posedge clk)
    if (_049_) \mem[13] [5] <= _001_[5];
  always @(posedge clk)
    if (_049_) \mem[13] [6] <= _001_[6];
  always @(posedge clk)
    if (_049_) \mem[13] [7] <= _001_[7];
  always @(posedge clk)
    if (_048_) \mem[12] [0] <= _001_[0];
  always @(posedge clk)
    if (_048_) \mem[12] [1] <= _001_[1];
  always @(posedge clk)
    if (_048_) \mem[12] [2] <= _001_[2];
  always @(posedge clk)
    if (_048_) \mem[12] [3] <= _001_[3];
  always @(posedge clk)
    if (_048_) \mem[12] [4] <= _001_[4];
  always @(posedge clk)
    if (_048_) \mem[12] [5] <= _001_[5];
  always @(posedge clk)
    if (_048_) \mem[12] [6] <= _001_[6];
  always @(posedge clk)
    if (_048_) \mem[12] [7] <= _001_[7];
  always @(posedge clk)
    if (_047_) \mem[11] [0] <= _001_[0];
  always @(posedge clk)
    if (_047_) \mem[11] [1] <= _001_[1];
  always @(posedge clk)
    if (_047_) \mem[11] [2] <= _001_[2];
  always @(posedge clk)
    if (_047_) \mem[11] [3] <= _001_[3];
  always @(posedge clk)
    if (_047_) \mem[11] [4] <= _001_[4];
  always @(posedge clk)
    if (_047_) \mem[11] [5] <= _001_[5];
  always @(posedge clk)
    if (_047_) \mem[11] [6] <= _001_[6];
  always @(posedge clk)
    if (_047_) \mem[11] [7] <= _001_[7];
  always @(posedge clk)
    if (_046_) \mem[10] [0] <= _001_[0];
  always @(posedge clk)
    if (_046_) \mem[10] [1] <= _001_[1];
  always @(posedge clk)
    if (_046_) \mem[10] [2] <= _001_[2];
  always @(posedge clk)
    if (_046_) \mem[10] [3] <= _001_[3];
  always @(posedge clk)
    if (_046_) \mem[10] [4] <= _001_[4];
  always @(posedge clk)
    if (_046_) \mem[10] [5] <= _001_[5];
  always @(posedge clk)
    if (_046_) \mem[10] [6] <= _001_[6];
  always @(posedge clk)
    if (_046_) \mem[10] [7] <= _001_[7];
  always @(posedge clk)
    if (_060_) \mem[9] [0] <= _001_[0];
  always @(posedge clk)
    if (_060_) \mem[9] [1] <= _001_[1];
  always @(posedge clk)
    if (_060_) \mem[9] [2] <= _001_[2];
  always @(posedge clk)
    if (_060_) \mem[9] [3] <= _001_[3];
  always @(posedge clk)
    if (_060_) \mem[9] [4] <= _001_[4];
  always @(posedge clk)
    if (_060_) \mem[9] [5] <= _001_[5];
  always @(posedge clk)
    if (_060_) \mem[9] [6] <= _001_[6];
  always @(posedge clk)
    if (_060_) \mem[9] [7] <= _001_[7];
  always @(posedge clk)
    if (_059_) \mem[8] [0] <= _001_[0];
  always @(posedge clk)
    if (_059_) \mem[8] [1] <= _001_[1];
  always @(posedge clk)
    if (_059_) \mem[8] [2] <= _001_[2];
  always @(posedge clk)
    if (_059_) \mem[8] [3] <= _001_[3];
  always @(posedge clk)
    if (_059_) \mem[8] [4] <= _001_[4];
  always @(posedge clk)
    if (_059_) \mem[8] [5] <= _001_[5];
  always @(posedge clk)
    if (_059_) \mem[8] [6] <= _001_[6];
  always @(posedge clk)
    if (_059_) \mem[8] [7] <= _001_[7];
  always @(posedge clk)
    if (_058_) \mem[7] [0] <= _001_[0];
  always @(posedge clk)
    if (_058_) \mem[7] [1] <= _001_[1];
  always @(posedge clk)
    if (_058_) \mem[7] [2] <= _001_[2];
  always @(posedge clk)
    if (_058_) \mem[7] [3] <= _001_[3];
  always @(posedge clk)
    if (_058_) \mem[7] [4] <= _001_[4];
  always @(posedge clk)
    if (_058_) \mem[7] [5] <= _001_[5];
  always @(posedge clk)
    if (_058_) \mem[7] [6] <= _001_[6];
  always @(posedge clk)
    if (_058_) \mem[7] [7] <= _001_[7];
  always @(posedge clk)
    if (_057_) \mem[6] [0] <= _001_[0];
  always @(posedge clk)
    if (_057_) \mem[6] [1] <= _001_[1];
  always @(posedge clk)
    if (_057_) \mem[6] [2] <= _001_[2];
  always @(posedge clk)
    if (_057_) \mem[6] [3] <= _001_[3];
  always @(posedge clk)
    if (_057_) \mem[6] [4] <= _001_[4];
  always @(posedge clk)
    if (_057_) \mem[6] [5] <= _001_[5];
  always @(posedge clk)
    if (_057_) \mem[6] [6] <= _001_[6];
  always @(posedge clk)
    if (_057_) \mem[6] [7] <= _001_[7];
  always @(posedge clk)
    if (_056_) \mem[5] [0] <= _001_[0];
  always @(posedge clk)
    if (_056_) \mem[5] [1] <= _001_[1];
  always @(posedge clk)
    if (_056_) \mem[5] [2] <= _001_[2];
  always @(posedge clk)
    if (_056_) \mem[5] [3] <= _001_[3];
  always @(posedge clk)
    if (_056_) \mem[5] [4] <= _001_[4];
  always @(posedge clk)
    if (_056_) \mem[5] [5] <= _001_[5];
  always @(posedge clk)
    if (_056_) \mem[5] [6] <= _001_[6];
  always @(posedge clk)
    if (_056_) \mem[5] [7] <= _001_[7];
  always @(posedge clk)
    if (_055_) \mem[4] [0] <= _001_[0];
  always @(posedge clk)
    if (_055_) \mem[4] [1] <= _001_[1];
  always @(posedge clk)
    if (_055_) \mem[4] [2] <= _001_[2];
  always @(posedge clk)
    if (_055_) \mem[4] [3] <= _001_[3];
  always @(posedge clk)
    if (_055_) \mem[4] [4] <= _001_[4];
  always @(posedge clk)
    if (_055_) \mem[4] [5] <= _001_[5];
  always @(posedge clk)
    if (_055_) \mem[4] [6] <= _001_[6];
  always @(posedge clk)
    if (_055_) \mem[4] [7] <= _001_[7];
  always @(posedge clk)
    if (_054_) \mem[3] [0] <= _001_[0];
  always @(posedge clk)
    if (_054_) \mem[3] [1] <= _001_[1];
  always @(posedge clk)
    if (_054_) \mem[3] [2] <= _001_[2];
  always @(posedge clk)
    if (_054_) \mem[3] [3] <= _001_[3];
  always @(posedge clk)
    if (_054_) \mem[3] [4] <= _001_[4];
  always @(posedge clk)
    if (_054_) \mem[3] [5] <= _001_[5];
  always @(posedge clk)
    if (_054_) \mem[3] [6] <= _001_[6];
  always @(posedge clk)
    if (_054_) \mem[3] [7] <= _001_[7];
  always @(posedge clk)
    if (_053_) \mem[2] [0] <= _001_[0];
  always @(posedge clk)
    if (_053_) \mem[2] [1] <= _001_[1];
  always @(posedge clk)
    if (_053_) \mem[2] [2] <= _001_[2];
  always @(posedge clk)
    if (_053_) \mem[2] [3] <= _001_[3];
  always @(posedge clk)
    if (_053_) \mem[2] [4] <= _001_[4];
  always @(posedge clk)
    if (_053_) \mem[2] [5] <= _001_[5];
  always @(posedge clk)
    if (_053_) \mem[2] [6] <= _001_[6];
  always @(posedge clk)
    if (_053_) \mem[2] [7] <= _001_[7];
  always @(posedge clk)
    if (_052_) \mem[1] [0] <= _001_[0];
  always @(posedge clk)
    if (_052_) \mem[1] [1] <= _001_[1];
  always @(posedge clk)
    if (_052_) \mem[1] [2] <= _001_[2];
  always @(posedge clk)
    if (_052_) \mem[1] [3] <= _001_[3];
  always @(posedge clk)
    if (_052_) \mem[1] [4] <= _001_[4];
  always @(posedge clk)
    if (_052_) \mem[1] [5] <= _001_[5];
  always @(posedge clk)
    if (_052_) \mem[1] [6] <= _001_[6];
  always @(posedge clk)
    if (_052_) \mem[1] [7] <= _001_[7];
  always @(posedge clk)
    if (_045_) \mem[0] [0] <= _001_[0];
  always @(posedge clk)
    if (_045_) \mem[0] [1] <= _001_[1];
  always @(posedge clk)
    if (_045_) \mem[0] [2] <= _001_[2];
  always @(posedge clk)
    if (_045_) \mem[0] [3] <= _001_[3];
  always @(posedge clk)
    if (_045_) \mem[0] [4] <= _001_[4];
  always @(posedge clk)
    if (_045_) \mem[0] [5] <= _001_[5];
  always @(posedge clk)
    if (_045_) \mem[0] [6] <= _001_[6];
  always @(posedge clk)
    if (_045_) \mem[0] [7] <= _001_[7];
  always @(posedge clk)
    data_out[0] <= _002_[0];
  always @(posedge clk)
    data_out[1] <= _002_[1];
  always @(posedge clk)
    data_out[2] <= _002_[2];
  always @(posedge clk)
    data_out[3] <= _002_[3];
  always @(posedge clk)
    data_out[4] <= _002_[4];
  always @(posedge clk)
    data_out[5] <= _002_[5];
  always @(posedge clk)
    data_out[6] <= _002_[6];
  always @(posedge clk)
    data_out[7] <= _002_[7];
  assign _026_ = _010_ & _022_;
  assign _025_ = _008_ & _022_;
  assign _024_ = _006_ & _022_;
  assign _023_ = _003_ & _022_;
  assign _022_ = _000_[2] & _000_[3];
  assign _021_ = _010_ & _017_;
  assign _020_ = _008_ & _017_;
  assign _019_ = _006_ & _017_;
  assign _018_ = _003_ & _017_;
  assign _017_ = _029_ & _000_[3];
  assign _016_ = _010_ & _012_;
  assign _015_ = _008_ & _012_;
  assign _014_ = _006_ & _012_;
  assign _013_ = _003_ & _012_;
  assign _012_ = _000_[2] & _030_;
  assign _011_ = _010_ & _004_;
  assign _010_ = _000_[0] & _000_[1];
  assign _009_ = _008_ & _004_;
  assign _008_ = _027_ & _000_[1];
  assign _007_ = _006_ & _004_;
  assign _006_ = _000_[0] & _028_;
  assign _005_ = _003_ & _004_;
  assign _004_ = _029_ & _030_;
  assign _003_ = _027_ & _028_;
  assign _045_ = _005_ & we;
  assign _052_ = _007_ & we;
  assign _053_ = _009_ & we;
  assign _054_ = _011_ & we;
  assign _055_ = _013_ & we;
  assign _056_ = _014_ & we;
  assign _057_ = _015_ & we;
  assign _058_ = _016_ & we;
  assign _059_ = _018_ & we;
  assign _060_ = _019_ & we;
  assign _046_ = _020_ & we;
  assign _047_ = _021_ & we;
  assign _048_ = _023_ & we;
  assign _049_ = _024_ & we;
  assign _050_ = _025_ & we;
  assign _051_ = _026_ & we;
  assign _001_[0] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) data_in[0] : 1'hx;
  assign _001_[1] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) data_in[1] : 1'hx;
  assign _001_[2] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) data_in[2] : 1'hx;
  assign _001_[3] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) data_in[3] : 1'hx;
  assign _001_[4] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) data_in[4] : 1'hx;
  assign _001_[5] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) data_in[5] : 1'hx;
  assign _001_[6] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) data_in[6] : 1'hx;
  assign _001_[7] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) data_in[7] : 1'hx;
  assign _000_[0] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) addr[0] : 1'hx;
  assign _000_[1] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) addr[1] : 1'hx;
  assign _000_[2] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) addr[2] : 1'hx;
  assign _000_[3] = we ? (* src = "single_port_ram.v:20.13-20.15|single_port_ram.v:20.9-21.34" *) addr[3] : 1'hx;
  assign _002_[0] = addr[3] ? _032_[0] : _031_[0];
  assign _002_[1] = addr[3] ? _032_[1] : _031_[1];
  assign _002_[2] = addr[3] ? _032_[2] : _031_[2];
  assign _002_[3] = addr[3] ? _032_[3] : _031_[3];
  assign _002_[4] = addr[3] ? _032_[4] : _031_[4];
  assign _002_[5] = addr[3] ? _032_[5] : _031_[5];
  assign _002_[6] = addr[3] ? _032_[6] : _031_[6];
  assign _002_[7] = addr[3] ? _032_[7] : _031_[7];
  assign _031_[0] = addr[2] ? _034_[0] : _033_[0];
  assign _031_[1] = addr[2] ? _034_[1] : _033_[1];
  assign _031_[2] = addr[2] ? _034_[2] : _033_[2];
  assign _031_[3] = addr[2] ? _034_[3] : _033_[3];
  assign _031_[4] = addr[2] ? _034_[4] : _033_[4];
  assign _031_[5] = addr[2] ? _034_[5] : _033_[5];
  assign _031_[6] = addr[2] ? _034_[6] : _033_[6];
  assign _031_[7] = addr[2] ? _034_[7] : _033_[7];
  assign _032_[0] = addr[2] ? _036_[0] : _035_[0];
  assign _032_[1] = addr[2] ? _036_[1] : _035_[1];
  assign _032_[2] = addr[2] ? _036_[2] : _035_[2];
  assign _032_[3] = addr[2] ? _036_[3] : _035_[3];
  assign _032_[4] = addr[2] ? _036_[4] : _035_[4];
  assign _032_[5] = addr[2] ? _036_[5] : _035_[5];
  assign _032_[6] = addr[2] ? _036_[6] : _035_[6];
  assign _032_[7] = addr[2] ? _036_[7] : _035_[7];
  assign _033_[0] = addr[1] ? _038_[0] : _037_[0];
  assign _033_[1] = addr[1] ? _038_[1] : _037_[1];
  assign _033_[2] = addr[1] ? _038_[2] : _037_[2];
  assign _033_[3] = addr[1] ? _038_[3] : _037_[3];
  assign _033_[4] = addr[1] ? _038_[4] : _037_[4];
  assign _033_[5] = addr[1] ? _038_[5] : _037_[5];
  assign _033_[6] = addr[1] ? _038_[6] : _037_[6];
  assign _033_[7] = addr[1] ? _038_[7] : _037_[7];
  assign _034_[0] = addr[1] ? _040_[0] : _039_[0];
  assign _034_[1] = addr[1] ? _040_[1] : _039_[1];
  assign _034_[2] = addr[1] ? _040_[2] : _039_[2];
  assign _034_[3] = addr[1] ? _040_[3] : _039_[3];
  assign _034_[4] = addr[1] ? _040_[4] : _039_[4];
  assign _034_[5] = addr[1] ? _040_[5] : _039_[5];
  assign _034_[6] = addr[1] ? _040_[6] : _039_[6];
  assign _034_[7] = addr[1] ? _040_[7] : _039_[7];
  assign _035_[0] = addr[1] ? _042_[0] : _041_[0];
  assign _035_[1] = addr[1] ? _042_[1] : _041_[1];
  assign _035_[2] = addr[1] ? _042_[2] : _041_[2];
  assign _035_[3] = addr[1] ? _042_[3] : _041_[3];
  assign _035_[4] = addr[1] ? _042_[4] : _041_[4];
  assign _035_[5] = addr[1] ? _042_[5] : _041_[5];
  assign _035_[6] = addr[1] ? _042_[6] : _041_[6];
  assign _035_[7] = addr[1] ? _042_[7] : _041_[7];
  assign _036_[0] = addr[1] ? _044_[0] : _043_[0];
  assign _036_[1] = addr[1] ? _044_[1] : _043_[1];
  assign _036_[2] = addr[1] ? _044_[2] : _043_[2];
  assign _036_[3] = addr[1] ? _044_[3] : _043_[3];
  assign _036_[4] = addr[1] ? _044_[4] : _043_[4];
  assign _036_[5] = addr[1] ? _044_[5] : _043_[5];
  assign _036_[6] = addr[1] ? _044_[6] : _043_[6];
  assign _036_[7] = addr[1] ? _044_[7] : _043_[7];
  assign _037_[0] = addr[0] ? \mem[1] [0] : \mem[0] [0];
  assign _037_[1] = addr[0] ? \mem[1] [1] : \mem[0] [1];
  assign _037_[2] = addr[0] ? \mem[1] [2] : \mem[0] [2];
  assign _037_[3] = addr[0] ? \mem[1] [3] : \mem[0] [3];
  assign _037_[4] = addr[0] ? \mem[1] [4] : \mem[0] [4];
  assign _037_[5] = addr[0] ? \mem[1] [5] : \mem[0] [5];
  assign _037_[6] = addr[0] ? \mem[1] [6] : \mem[0] [6];
  assign _037_[7] = addr[0] ? \mem[1] [7] : \mem[0] [7];
  assign _038_[0] = addr[0] ? \mem[3] [0] : \mem[2] [0];
  assign _038_[1] = addr[0] ? \mem[3] [1] : \mem[2] [1];
  assign _038_[2] = addr[0] ? \mem[3] [2] : \mem[2] [2];
  assign _038_[3] = addr[0] ? \mem[3] [3] : \mem[2] [3];
  assign _038_[4] = addr[0] ? \mem[3] [4] : \mem[2] [4];
  assign _038_[5] = addr[0] ? \mem[3] [5] : \mem[2] [5];
  assign _038_[6] = addr[0] ? \mem[3] [6] : \mem[2] [6];
  assign _038_[7] = addr[0] ? \mem[3] [7] : \mem[2] [7];
  assign _039_[0] = addr[0] ? \mem[5] [0] : \mem[4] [0];
  assign _039_[1] = addr[0] ? \mem[5] [1] : \mem[4] [1];
  assign _039_[2] = addr[0] ? \mem[5] [2] : \mem[4] [2];
  assign _039_[3] = addr[0] ? \mem[5] [3] : \mem[4] [3];
  assign _039_[4] = addr[0] ? \mem[5] [4] : \mem[4] [4];
  assign _039_[5] = addr[0] ? \mem[5] [5] : \mem[4] [5];
  assign _039_[6] = addr[0] ? \mem[5] [6] : \mem[4] [6];
  assign _039_[7] = addr[0] ? \mem[5] [7] : \mem[4] [7];
  assign _040_[0] = addr[0] ? \mem[7] [0] : \mem[6] [0];
  assign _040_[1] = addr[0] ? \mem[7] [1] : \mem[6] [1];
  assign _040_[2] = addr[0] ? \mem[7] [2] : \mem[6] [2];
  assign _040_[3] = addr[0] ? \mem[7] [3] : \mem[6] [3];
  assign _040_[4] = addr[0] ? \mem[7] [4] : \mem[6] [4];
  assign _040_[5] = addr[0] ? \mem[7] [5] : \mem[6] [5];
  assign _040_[6] = addr[0] ? \mem[7] [6] : \mem[6] [6];
  assign _040_[7] = addr[0] ? \mem[7] [7] : \mem[6] [7];
  assign _041_[0] = addr[0] ? \mem[9] [0] : \mem[8] [0];
  assign _041_[1] = addr[0] ? \mem[9] [1] : \mem[8] [1];
  assign _041_[2] = addr[0] ? \mem[9] [2] : \mem[8] [2];
  assign _041_[3] = addr[0] ? \mem[9] [3] : \mem[8] [3];
  assign _041_[4] = addr[0] ? \mem[9] [4] : \mem[8] [4];
  assign _041_[5] = addr[0] ? \mem[9] [5] : \mem[8] [5];
  assign _041_[6] = addr[0] ? \mem[9] [6] : \mem[8] [6];
  assign _041_[7] = addr[0] ? \mem[9] [7] : \mem[8] [7];
  assign _042_[0] = addr[0] ? \mem[11] [0] : \mem[10] [0];
  assign _042_[1] = addr[0] ? \mem[11] [1] : \mem[10] [1];
  assign _042_[2] = addr[0] ? \mem[11] [2] : \mem[10] [2];
  assign _042_[3] = addr[0] ? \mem[11] [3] : \mem[10] [3];
  assign _042_[4] = addr[0] ? \mem[11] [4] : \mem[10] [4];
  assign _042_[5] = addr[0] ? \mem[11] [5] : \mem[10] [5];
  assign _042_[6] = addr[0] ? \mem[11] [6] : \mem[10] [6];
  assign _042_[7] = addr[0] ? \mem[11] [7] : \mem[10] [7];
  assign _043_[0] = addr[0] ? \mem[13] [0] : \mem[12] [0];
  assign _043_[1] = addr[0] ? \mem[13] [1] : \mem[12] [1];
  assign _043_[2] = addr[0] ? \mem[13] [2] : \mem[12] [2];
  assign _043_[3] = addr[0] ? \mem[13] [3] : \mem[12] [3];
  assign _043_[4] = addr[0] ? \mem[13] [4] : \mem[12] [4];
  assign _043_[5] = addr[0] ? \mem[13] [5] : \mem[12] [5];
  assign _043_[6] = addr[0] ? \mem[13] [6] : \mem[12] [6];
  assign _043_[7] = addr[0] ? \mem[13] [7] : \mem[12] [7];
  assign _044_[0] = addr[0] ? \mem[15] [0] : \mem[14] [0];
  assign _044_[1] = addr[0] ? \mem[15] [1] : \mem[14] [1];
  assign _044_[2] = addr[0] ? \mem[15] [2] : \mem[14] [2];
  assign _044_[3] = addr[0] ? \mem[15] [3] : \mem[14] [3];
  assign _044_[4] = addr[0] ? \mem[15] [4] : \mem[14] [4];
  assign _044_[5] = addr[0] ? \mem[15] [5] : \mem[14] [5];
  assign _044_[6] = addr[0] ? \mem[15] [6] : \mem[14] [6];
  assign _044_[7] = addr[0] ? \mem[15] [7] : \mem[14] [7];
  assign _030_ = ~_000_[3];
  assign _029_ = ~_000_[2];
  assign _028_ = ~_000_[1];
  assign _027_ = ~_000_[0];
endmodule
