/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* top =  1  *)
(* src = "top.v:3.1-70.10" *)
module top(clk, reset, up_down, A, B, count, result, ram_out);
  (* src = "top.v:5.23-5.26" *)
  input clk;
  wire clk;
  (* src = "top.v:6.23-6.28" *)
  input reset;
  wire reset;
  (* src = "top.v:7.23-7.30" *)
  input up_down;
  wire up_down;
  (* src = "top.v:9.23-9.24" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "top.v:10.23-10.24" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "top.v:12.23-12.28" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "top.v:13.23-13.29" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "top.v:14.23-14.30" *)
  output [7:0] ram_out;
  wire [7:0] ram_out;
  wire [1:0] _0000_;
  wire [1:0] _0001_;
  wire [1:0] _0002_;
  wire [1:0] _0003_;
  wire [1:0] _0004_;
  wire [1:0] _0005_;
  wire [3:0] _0006_;
  wire [1:0] _0007_;
  wire _0008_;
  wire [7:0] _0009_;
  wire [3:0] _0010_;
  wire [1:0] _0011_;
  wire _0012_;
  wire [7:0] _0013_;
  wire [3:0] _0014_;
  wire [1:0] _0015_;
  wire _0016_;
  wire [7:0] _0017_;
  wire [3:0] _0018_;
  wire [1:0] _0019_;
  wire _0020_;
  wire [7:0] _0021_;
  wire [3:0] _0022_;
  wire [1:0] _0023_;
  wire _0024_;
  wire [7:0] _0025_;
  wire [3:0] _0026_;
  wire [1:0] _0027_;
  wire _0028_;
  wire [7:0] _0029_;
  wire [3:0] _0030_;
  wire [1:0] _0031_;
  wire _0032_;
  wire [7:0] _0033_;
  wire [3:0] _0034_;
  wire [1:0] _0035_;
  wire _0036_;
  wire [7:0] _0037_;
  wire [3:0] _0038_;
  wire [1:0] _0039_;
  wire _0040_;
  wire [7:0] _0041_;
  wire [3:0] _0042_;
  wire [1:0] _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  (* src = "alu.v:39.28-39.34" *)
  wire [7:0] _0169_;
  (* src = "alu.v:24.27-24.35" *)
  wire [7:0] _0170_;
  (* src = "alu.v:25.27-25.35" *)
  wire [7:0] _0171_;
  (* src = "alu.v:26.27-26.35" *)
  wire [7:0] _0172_;
  (* src = "alu.v:22.27-22.32" *)
  wire [7:0] _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire [3:0] _0190_;
  wire [7:0] _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire [7:0] _0214_;
  wire [7:0] _0215_;
  wire [7:0] _0216_;
  wire [7:0] _0217_;
  wire [7:0] _0218_;
  wire [7:0] _0219_;
  wire [7:0] _0220_;
  wire [7:0] _0221_;
  wire [7:0] _0222_;
  wire [7:0] _0223_;
  wire [7:0] _0224_;
  wire [7:0] _0225_;
  wire [7:0] _0226_;
  wire [7:0] _0227_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "7" *)
  wire [7:0] _0228_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _0229_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _0230_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [7:0] _0231_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "7" *)
  wire [31:0] _0232_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _0233_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "8" *)
  wire [31:0] _0234_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [7:0] _0235_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "7" *)
  wire [7:0] _0236_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _0237_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _0238_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:200.21-200.22" *)
  (* unused_bits = "7" *)
  wire [7:0] _0239_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _0240_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _0241_;
  (* force_downto = 32'd1 *)
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _0242_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:20.22-20.31|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _0243_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:20.22-20.31|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _0244_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:20.22-20.31|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _0245_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _0246_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _0247_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _0248_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0249_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0250_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0251_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0252_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _0253_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _0254_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0255_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0256_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0257_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0258_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _0259_;
  (* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _0260_;
  (* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _0261_;
  (* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _0262_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0263_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0264_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0265_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0266_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _0267_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _0268_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0269_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0270_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0271_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0272_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _0273_;
  (* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _0274_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0275_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0276_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0277_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _0278_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _0279_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _0280_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0281_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0282_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0283_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0284_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _0285_;
  (* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _0286_;
  (* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _0287_;
  (* hdlname = "U_ALU A" *)
  (* src = "alu.v:6.29-6.30" *)
  wire [7:0] \U_ALU.A ;
  (* hdlname = "U_ALU B" *)
  (* src = "alu.v:7.29-7.30" *)
  wire [7:0] \U_ALU.B ;
  (* hdlname = "U_ALU opcode" *)
  (* src = "alu.v:8.29-8.35" *)
  wire [3:0] \U_ALU.opcode ;
  (* hdlname = "U_ALU result" *)
  (* src = "alu.v:10.29-10.35" *)
  wire [7:0] \U_ALU.result ;
  (* hdlname = "U_COUNTER clk" *)
  (* src = "counter.v:6.29-6.32" *)
  wire \U_COUNTER.clk ;
  (* hdlname = "U_COUNTER count" *)
  (* src = "counter.v:10.29-10.34" *)
  reg [3:0] \U_COUNTER.count ;
  (* hdlname = "U_COUNTER enable" *)
  (* src = "counter.v:9.29-9.35" *)
  wire \U_COUNTER.enable ;
  (* hdlname = "U_COUNTER reset" *)
  (* src = "counter.v:7.29-7.34" *)
  wire \U_COUNTER.reset ;
  (* hdlname = "U_COUNTER up_down" *)
  (* src = "counter.v:8.29-8.36" *)
  wire \U_COUNTER.up_down ;
  (* hdlname = "U_RAM addr" *)
  (* src = "single_port_ram.v:10.38-10.42" *)
  wire [3:0] \U_RAM.addr ;
  (* hdlname = "U_RAM clk" *)
  (* src = "single_port_ram.v:8.38-8.41" *)
  wire \U_RAM.clk ;
  (* hdlname = "U_RAM data_in" *)
  (* src = "single_port_ram.v:11.38-11.45" *)
  wire [7:0] \U_RAM.data_in ;
  (* hdlname = "U_RAM data_out" *)
  (* src = "single_port_ram.v:12.38-12.46" *)
  reg [7:0] \U_RAM.data_out ;
  (* hdlname = "U_RAM mem[0]" *)
  reg [7:0] \U_RAM.mem[0] ;
  (* hdlname = "U_RAM mem[10]" *)
  reg [7:0] \U_RAM.mem[10] ;
  (* hdlname = "U_RAM mem[11]" *)
  reg [7:0] \U_RAM.mem[11] ;
  (* hdlname = "U_RAM mem[12]" *)
  reg [7:0] \U_RAM.mem[12] ;
  (* hdlname = "U_RAM mem[13]" *)
  reg [7:0] \U_RAM.mem[13] ;
  (* hdlname = "U_RAM mem[14]" *)
  reg [7:0] \U_RAM.mem[14] ;
  (* hdlname = "U_RAM mem[15]" *)
  reg [7:0] \U_RAM.mem[15] ;
  (* hdlname = "U_RAM mem[1]" *)
  reg [7:0] \U_RAM.mem[1] ;
  (* hdlname = "U_RAM mem[2]" *)
  reg [7:0] \U_RAM.mem[2] ;
  (* hdlname = "U_RAM mem[3]" *)
  reg [7:0] \U_RAM.mem[3] ;
  (* hdlname = "U_RAM mem[4]" *)
  reg [7:0] \U_RAM.mem[4] ;
  (* hdlname = "U_RAM mem[5]" *)
  reg [7:0] \U_RAM.mem[5] ;
  (* hdlname = "U_RAM mem[6]" *)
  reg [7:0] \U_RAM.mem[6] ;
  (* hdlname = "U_RAM mem[7]" *)
  reg [7:0] \U_RAM.mem[7] ;
  (* hdlname = "U_RAM mem[8]" *)
  reg [7:0] \U_RAM.mem[8] ;
  (* hdlname = "U_RAM mem[9]" *)
  reg [7:0] \U_RAM.mem[9] ;
  (* hdlname = "U_RAM we" *)
  (* src = "single_port_ram.v:9.38-9.40" *)
  wire \U_RAM.we ;
  (* src = "counter.v:13.1-24.4" *)
  always @(posedge clk, posedge reset)
    if (reset) \U_COUNTER.count [0] <= 1'h0;
    else \U_COUNTER.count [0] <= _0244_[0];
  (* src = "counter.v:13.1-24.4" *)
  always @(posedge clk, posedge reset)
    if (reset) \U_COUNTER.count [1] <= 1'h0;
    else \U_COUNTER.count [1] <= _0190_[1];
  (* src = "counter.v:13.1-24.4" *)
  always @(posedge clk, posedge reset)
    if (reset) \U_COUNTER.count [2] <= 1'h0;
    else \U_COUNTER.count [2] <= _0190_[2];
  (* src = "counter.v:13.1-24.4" *)
  always @(posedge clk, posedge reset)
    if (reset) \U_COUNTER.count [3] <= 1'h0;
    else \U_COUNTER.count [3] <= _0190_[3];
  always @(posedge clk)
    \U_RAM.data_out [0] <= _0191_[0];
  always @(posedge clk)
    \U_RAM.data_out [1] <= _0191_[1];
  always @(posedge clk)
    \U_RAM.data_out [2] <= _0191_[2];
  always @(posedge clk)
    \U_RAM.data_out [3] <= _0191_[3];
  always @(posedge clk)
    \U_RAM.data_out [4] <= _0191_[4];
  always @(posedge clk)
    \U_RAM.data_out [5] <= _0191_[5];
  always @(posedge clk)
    \U_RAM.data_out [6] <= _0191_[6];
  always @(posedge clk)
    \U_RAM.data_out [7] <= _0191_[7];
  always @(posedge clk)
    if (_0243_[3]) \U_RAM.mem[15] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0243_[3]) \U_RAM.mem[15] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0243_[3]) \U_RAM.mem[15] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0243_[3]) \U_RAM.mem[15] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0243_[3]) \U_RAM.mem[15] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0243_[3]) \U_RAM.mem[15] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0243_[3]) \U_RAM.mem[15] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0243_[3]) \U_RAM.mem[15] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0213_) \U_RAM.mem[14] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0213_) \U_RAM.mem[14] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0213_) \U_RAM.mem[14] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0213_) \U_RAM.mem[14] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0213_) \U_RAM.mem[14] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0213_) \U_RAM.mem[14] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0213_) \U_RAM.mem[14] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0213_) \U_RAM.mem[14] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0212_) \U_RAM.mem[13] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0212_) \U_RAM.mem[13] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0212_) \U_RAM.mem[13] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0212_) \U_RAM.mem[13] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0212_) \U_RAM.mem[13] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0212_) \U_RAM.mem[13] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0212_) \U_RAM.mem[13] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0212_) \U_RAM.mem[13] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0211_) \U_RAM.mem[12] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0211_) \U_RAM.mem[12] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0211_) \U_RAM.mem[12] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0211_) \U_RAM.mem[12] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0211_) \U_RAM.mem[12] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0211_) \U_RAM.mem[12] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0211_) \U_RAM.mem[12] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0211_) \U_RAM.mem[12] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0209_) \U_RAM.mem[11] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0209_) \U_RAM.mem[11] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0209_) \U_RAM.mem[11] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0209_) \U_RAM.mem[11] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0209_) \U_RAM.mem[11] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0209_) \U_RAM.mem[11] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0209_) \U_RAM.mem[11] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0209_) \U_RAM.mem[11] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0208_) \U_RAM.mem[10] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0208_) \U_RAM.mem[10] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0208_) \U_RAM.mem[10] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0208_) \U_RAM.mem[10] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0208_) \U_RAM.mem[10] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0208_) \U_RAM.mem[10] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0208_) \U_RAM.mem[10] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0208_) \U_RAM.mem[10] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0207_) \U_RAM.mem[9] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0207_) \U_RAM.mem[9] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0207_) \U_RAM.mem[9] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0207_) \U_RAM.mem[9] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0207_) \U_RAM.mem[9] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0207_) \U_RAM.mem[9] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0207_) \U_RAM.mem[9] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0207_) \U_RAM.mem[9] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0206_) \U_RAM.mem[8] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0206_) \U_RAM.mem[8] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0206_) \U_RAM.mem[8] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0206_) \U_RAM.mem[8] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0206_) \U_RAM.mem[8] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0206_) \U_RAM.mem[8] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0206_) \U_RAM.mem[8] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0206_) \U_RAM.mem[8] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0204_) \U_RAM.mem[7] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0204_) \U_RAM.mem[7] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0204_) \U_RAM.mem[7] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0204_) \U_RAM.mem[7] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0204_) \U_RAM.mem[7] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0204_) \U_RAM.mem[7] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0204_) \U_RAM.mem[7] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0204_) \U_RAM.mem[7] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0203_) \U_RAM.mem[6] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0203_) \U_RAM.mem[6] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0203_) \U_RAM.mem[6] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0203_) \U_RAM.mem[6] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0203_) \U_RAM.mem[6] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0203_) \U_RAM.mem[6] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0203_) \U_RAM.mem[6] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0203_) \U_RAM.mem[6] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0202_) \U_RAM.mem[5] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0202_) \U_RAM.mem[5] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0202_) \U_RAM.mem[5] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0202_) \U_RAM.mem[5] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0202_) \U_RAM.mem[5] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0202_) \U_RAM.mem[5] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0202_) \U_RAM.mem[5] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0202_) \U_RAM.mem[5] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0201_) \U_RAM.mem[4] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0201_) \U_RAM.mem[4] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0201_) \U_RAM.mem[4] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0201_) \U_RAM.mem[4] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0201_) \U_RAM.mem[4] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0201_) \U_RAM.mem[4] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0201_) \U_RAM.mem[4] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0201_) \U_RAM.mem[4] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0199_) \U_RAM.mem[3] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0199_) \U_RAM.mem[3] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0199_) \U_RAM.mem[3] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0199_) \U_RAM.mem[3] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0199_) \U_RAM.mem[3] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0199_) \U_RAM.mem[3] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0199_) \U_RAM.mem[3] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0199_) \U_RAM.mem[3] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0198_) \U_RAM.mem[2] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0198_) \U_RAM.mem[2] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0198_) \U_RAM.mem[2] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0198_) \U_RAM.mem[2] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0198_) \U_RAM.mem[2] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0198_) \U_RAM.mem[2] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0198_) \U_RAM.mem[2] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0198_) \U_RAM.mem[2] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0196_) \U_RAM.mem[1] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0196_) \U_RAM.mem[1] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0196_) \U_RAM.mem[1] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0196_) \U_RAM.mem[1] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0196_) \U_RAM.mem[1] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0196_) \U_RAM.mem[1] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0196_) \U_RAM.mem[1] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0196_) \U_RAM.mem[1] [7] <= \U_ALU.result [7];
  always @(posedge clk)
    if (_0194_) \U_RAM.mem[0] [0] <= \U_ALU.result [0];
  always @(posedge clk)
    if (_0194_) \U_RAM.mem[0] [1] <= \U_ALU.result [1];
  always @(posedge clk)
    if (_0194_) \U_RAM.mem[0] [2] <= \U_ALU.result [2];
  always @(posedge clk)
    if (_0194_) \U_RAM.mem[0] [3] <= \U_ALU.result [3];
  always @(posedge clk)
    if (_0194_) \U_RAM.mem[0] [4] <= \U_ALU.result [4];
  always @(posedge clk)
    if (_0194_) \U_RAM.mem[0] [5] <= \U_ALU.result [5];
  always @(posedge clk)
    if (_0194_) \U_RAM.mem[0] [6] <= \U_ALU.result [6];
  always @(posedge clk)
    if (_0194_) \U_RAM.mem[0] [7] <= \U_ALU.result [7];
  assign _0247_[1] = ~\U_COUNTER.count [1];
  assign _0247_[3] = ~\U_COUNTER.count [3];
  assign _0247_[2] = ~\U_COUNTER.count [2];
  assign _0241_[1] = ~A[1];
  assign _0241_[7] = ~A[7];
  assign _0241_[6] = ~A[6];
  assign _0241_[5] = ~A[5];
  assign _0241_[4] = ~A[4];
  assign _0241_[3] = ~A[3];
  assign _0241_[2] = ~A[2];
  assign _0233_[0] = ~A[0];
  assign _0238_[0] = ~_0237_[0];
  assign _0244_[0] = ~\U_COUNTER.count [0];
  assign _0207_ = _0195_ & _0205_;
  assign _0209_ = _0243_[1] & _0205_;
  assign _0206_ = _0192_ & _0205_;
  assign _0205_ = _0247_[2] & \U_COUNTER.count [3];
  assign _0204_ = _0243_[1] & _0200_;
  assign _0211_ = _0192_ & _0210_;
  assign _0203_ = _0197_ & _0200_;
  assign _0202_ = _0195_ & _0200_;
  assign _0201_ = _0192_ & _0200_;
  assign _0200_ = \U_COUNTER.count [2] & _0247_[3];
  assign _0212_ = _0195_ & _0210_;
  assign _0199_ = _0243_[1] & _0193_;
  assign _0198_ = _0197_ & _0193_;
  assign _0197_ = _0244_[0] & \U_COUNTER.count [1];
  assign _0208_ = _0197_ & _0205_;
  assign _0196_ = _0195_ & _0193_;
  assign _0195_ = \U_COUNTER.count [0] & _0247_[1];
  assign _0213_ = _0197_ & _0210_;
  assign _0194_ = _0192_ & _0193_;
  assign _0192_ = _0244_[0] & _0247_[1];
  assign _0230_[1] = _0229_[1] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0228_[0];
  assign _0230_[2] = _0229_[2] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0228_[1];
  assign _0230_[3] = _0229_[3] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0228_[2];
  assign _0230_[4] = _0229_[4] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0228_[3];
  assign _0230_[5] = _0229_[5] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0228_[4];
  assign _0230_[6] = _0229_[6] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0228_[5];
  assign _0230_[7] = _0229_[7] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0228_[6];
  assign _0238_[1] = _0237_[1] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0236_[0];
  assign _0238_[2] = _0237_[2] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0236_[1];
  assign _0238_[3] = _0237_[3] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0236_[2];
  assign _0238_[4] = _0237_[4] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0236_[3];
  assign _0238_[5] = _0237_[5] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0236_[4];
  assign _0238_[6] = _0237_[6] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0236_[5];
  assign _0238_[7] = _0237_[7] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0236_[6];
  assign _0234_[1] = A[1] ^(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  A[0];
  assign _0234_[2] = A[2] ^(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0232_[1];
  assign _0234_[3] = A[3] ^(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0232_[2];
  assign _0234_[4] = A[4] ^(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0232_[3];
  assign _0234_[5] = A[5] ^(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0232_[4];
  assign _0234_[6] = A[6] ^(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0232_[5];
  assign _0234_[7] = A[7] ^(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0232_[6];
  assign _0242_[1] = _0241_[1] ^(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  A[0];
  assign _0242_[2] = _0241_[2] ^(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0240_[1];
  assign _0242_[3] = _0241_[3] ^(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0240_[2];
  assign _0242_[4] = _0241_[4] ^(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0240_[3];
  assign _0242_[5] = _0241_[5] ^(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0240_[4];
  assign _0242_[6] = _0241_[6] ^(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0240_[5];
  assign _0242_[7] = _0241_[7] ^(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0240_[6];
  assign _0245_[1] = \U_COUNTER.count [1] ^(* src = "counter.v:20.22-20.31|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  \U_COUNTER.count [0];
  assign _0245_[2] = \U_COUNTER.count [2] ^(* src = "counter.v:20.22-20.31|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0243_[1];
  assign _0245_[3] = \U_COUNTER.count [3] ^(* src = "counter.v:20.22-20.31|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0243_[2];
  assign _0248_[1] = _0247_[1] ^(* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  \U_COUNTER.count [0];
  assign _0248_[2] = _0247_[2] ^(* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0246_[1];
  assign _0248_[3] = _0247_[3] ^(* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _0246_[2];
  assign _0228_[0] = A[0] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[0];
  assign _0231_[1] = A[1] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[1];
  assign _0231_[2] = A[2] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[2];
  assign _0231_[3] = A[3] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[3];
  assign _0231_[4] = A[4] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[4];
  assign _0231_[5] = A[5] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[5];
  assign _0231_[6] = A[6] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[6];
  assign _0231_[7] = A[7] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[7];
  assign _0229_[0] = A[0] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[0];
  assign _0229_[1] = A[1] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[1];
  assign _0229_[3] = A[3] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[3];
  assign _0229_[6] = A[6] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[6];
  assign _0229_[7] = A[7] ^(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[7];
  assign _0228_[2] = _0231_[2] |(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0256_;
  assign _0256_ = _0229_[2] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0228_[1];
  assign _0257_ = _0229_[4] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0228_[3];
  assign _0228_[5] = _0260_ |(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0255_;
  assign _0255_ = _0254_ &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0228_[3];
  assign _0258_ = _0229_[6] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0228_[5];
  assign _0228_[6] = _0231_[6] |(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0258_;
  assign _0228_[3] = _0259_ |(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0252_;
  assign _0252_ = _0253_ &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0228_[1];
  assign _0254_ = _0229_[5] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _0229_[4];
  assign _0260_ = _0231_[5] |(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0251_;
  assign _0251_ = _0229_[5] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0231_[4];
  assign _0253_ = _0229_[3] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _0229_[2];
  assign _0259_ = _0231_[3] |(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0250_;
  assign _0250_ = _0229_[3] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0231_[2];
  assign _0228_[4] = _0231_[4] |(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0257_;
  assign _0228_[1] = _0231_[1] |(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0249_;
  assign _0249_ = _0229_[1] &(* src = "alu.v:17.27-17.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0228_[0];
  assign _0239_[0] = A[0] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _0235_[0];
  assign _0239_[1] = A[1] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _0235_[1];
  assign _0239_[2] = A[2] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _0235_[2];
  assign _0239_[3] = A[3] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _0235_[3];
  assign _0239_[4] = A[4] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _0235_[4];
  assign _0239_[5] = A[5] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _0235_[5];
  assign _0239_[6] = A[6] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _0235_[6];
  assign _0237_[0] = A[0] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _0235_[0];
  assign _0237_[1] = A[1] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _0235_[1];
  assign _0237_[2] = A[2] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _0235_[2];
  assign _0237_[3] = A[3] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _0235_[3];
  assign _0237_[4] = A[4] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _0235_[4];
  assign _0237_[5] = A[5] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _0235_[5];
  assign _0237_[6] = A[6] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _0235_[6];
  assign _0237_[7] = A[7] ^(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _0235_[7];
  assign _0236_[2] = _0239_[2] |(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0270_;
  assign _0270_ = _0237_[2] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0236_[1];
  assign _0271_ = _0237_[4] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0236_[3];
  assign _0236_[5] = _0274_ |(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0269_;
  assign _0269_ = _0268_ &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0236_[3];
  assign _0272_ = _0237_[6] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0236_[5];
  assign _0236_[6] = _0239_[6] |(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0272_;
  assign _0236_[3] = _0273_ |(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0266_;
  assign _0266_ = _0267_ &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0236_[1];
  assign _0268_ = _0237_[5] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _0237_[4];
  assign _0274_ = _0239_[5] |(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0265_;
  assign _0265_ = _0237_[5] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0239_[4];
  assign _0267_ = _0237_[3] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _0237_[2];
  assign _0273_ = _0239_[3] |(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0264_;
  assign _0264_ = _0237_[3] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0239_[2];
  assign _0236_[4] = _0239_[4] |(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0271_;
  assign _0236_[1] = _0239_[1] |(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0263_;
  assign _0263_ = _0237_[1] &(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0236_[0];
  assign _0236_[0] = _0239_[0] |(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:231.10-231.28" *)  _0237_[0];
  assign _0232_[6] = A[6] &(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0232_[5];
  assign _0232_[4] = A[4] &(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0232_[3];
  assign _0232_[2] = A[2] &(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0232_[1];
  assign _0232_[5] = _0262_ &(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0232_[3];
  assign _0232_[3] = _0261_ &(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0232_[1];
  assign _0262_ = A[5] &(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  A[4];
  assign _0261_ = A[3] &(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  A[2];
  assign _0232_[1] = A[1] &(* src = "alu.v:33.27-33.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  A[0];
  assign _0240_[6] = A[6] |(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0284_;
  assign _0284_ = _0241_[6] &(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0240_[5];
  assign _0240_[4] = A[4] |(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0283_;
  assign _0283_ = _0241_[4] &(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0240_[3];
  assign _0240_[2] = A[2] |(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0282_;
  assign _0282_ = _0241_[2] &(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0240_[1];
  assign _0240_[5] = _0286_ |(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0281_;
  assign _0281_ = _0280_ &(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0240_[3];
  assign _0240_[3] = _0285_ |(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0278_;
  assign _0278_ = _0279_ &(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0240_[1];
  assign _0280_ = _0241_[5] &(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _0241_[4];
  assign _0286_ = A[5] |(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0277_;
  assign _0277_ = _0241_[5] &(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  A[4];
  assign _0279_ = _0241_[3] &(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _0241_[2];
  assign _0285_ = A[3] |(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0276_;
  assign _0276_ = _0241_[3] &(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  A[2];
  assign _0240_[1] = A[1] |(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0275_;
  assign _0275_ = _0241_[1] &(* src = "alu.v:34.27-34.32|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  A[0];
  assign _0243_[2] = \U_COUNTER.count [2] &(* src = "counter.v:20.22-20.31|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0243_[1];
  assign _0243_[3] = _0210_ &(* src = "counter.v:20.22-20.31|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _0243_[1];
  assign _0210_ = \U_COUNTER.count [3] &(* src = "counter.v:20.22-20.31|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  \U_COUNTER.count [2];
  assign _0243_[1] = \U_COUNTER.count [1] &(* src = "counter.v:20.22-20.31|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  \U_COUNTER.count [0];
  assign _0246_[2] = \U_COUNTER.count [2] |(* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _0287_;
  assign _0287_ = _0247_[2] &(* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _0246_[1];
  assign _0193_ = _0247_[3] &(* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _0247_[2];
  assign _0246_[1] = \U_COUNTER.count [1] |(* src = "counter.v:22.22-22.31|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _0195_;
  assign _0173_[0] = A[0] |(* src = "alu.v:26.29-26.34" *)  B[0];
  assign _0173_[1] = A[1] |(* src = "alu.v:26.29-26.34" *)  B[1];
  assign _0173_[2] = A[2] |(* src = "alu.v:26.29-26.34" *)  B[2];
  assign _0173_[3] = A[3] |(* src = "alu.v:26.29-26.34" *)  B[3];
  assign _0173_[4] = A[4] |(* src = "alu.v:26.29-26.34" *)  B[4];
  assign _0173_[5] = A[5] |(* src = "alu.v:26.29-26.34" *)  B[5];
  assign _0173_[6] = A[6] |(* src = "alu.v:26.29-26.34" *)  B[6];
  assign _0173_[7] = A[7] |(* src = "alu.v:26.29-26.34" *)  B[7];
  assign _0229_[2] = A[2] ^(* src = "alu.v:39.28-39.34" *)  B[2];
  assign _0229_[4] = A[4] ^(* src = "alu.v:39.28-39.34" *)  B[4];
  assign _0229_[5] = A[5] ^(* src = "alu.v:39.28-39.34" *)  B[5];
  assign _0045_ = _0000_[0] |(* src = "alu.v:36.29-36.29|alu.v:14.5-46.12" *)  _0000_[1];
  assign _0046_ = _0001_[0] |(* src = "alu.v:35.29-35.29|alu.v:14.5-46.12" *)  _0001_[1];
  assign _0047_ = _0000_[0] |(* src = "alu.v:34.33-34.33|alu.v:14.5-46.12" *)  _0001_[1];
  assign _0048_ = _0002_[0] |(* src = "alu.v:33.33-33.33|alu.v:14.5-46.12" *)  _0001_[1];
  assign _0001_[1] = \U_COUNTER.count [2] |(* src = "alu.v:30.34-30.34|alu.v:14.5-46.12" *)  _0247_[3];
  assign _0049_ = _0003_[0] |(* src = "alu.v:30.34-30.34|alu.v:14.5-46.12" *)  _0001_[1];
  assign _0001_[0] = _0244_[0] |(* src = "alu.v:29.34-29.34|alu.v:14.5-46.12" *)  _0247_[1];
  assign _0050_ = _0001_[0] |(* src = "alu.v:29.34-29.34|alu.v:14.5-46.12" *)  _0004_[1];
  assign _0000_[0] = \U_COUNTER.count [0] |(* src = "alu.v:26.36-26.36|alu.v:14.5-46.12" *)  _0247_[1];
  assign _0051_ = _0000_[0] |(* src = "alu.v:26.36-26.36|alu.v:14.5-46.12" *)  _0004_[1];
  assign _0052_ = _0002_[0] |(* src = "alu.v:25.36-25.36|alu.v:14.5-46.12" *)  _0000_[1];
  assign _0003_[0] = \U_COUNTER.count [0] |(* src = "alu.v:24.36-24.36|alu.v:14.5-46.12" *)  \U_COUNTER.count [1];
  assign _0000_[1] = _0247_[2] |(* src = "alu.v:24.36-24.36|alu.v:14.5-46.12" *)  _0247_[3];
  assign _0053_ = _0003_[0] |(* src = "alu.v:24.36-24.36|alu.v:14.5-46.12" *)  _0000_[1];
  assign _0002_[0] = _0244_[0] |(* src = "alu.v:23.33-23.33|alu.v:14.5-46.12" *)  \U_COUNTER.count [1];
  assign _0004_[1] = _0247_[2] |(* src = "alu.v:23.33-23.33|alu.v:14.5-46.12" *)  \U_COUNTER.count [3];
  assign _0054_ = _0002_[0] |(* src = "alu.v:23.33-23.33|alu.v:14.5-46.12" *)  _0004_[1];
  assign _0055_ = _0003_[0] |(* src = "alu.v:22.33-22.33|alu.v:14.5-46.12" *)  _0004_[1];
  assign _0056_ = _0001_[0] |(* src = "alu.v:21.33-21.33|alu.v:14.5-46.12" *)  _0005_[1];
  assign _0057_ = _0000_[0] |(* src = "alu.v:18.33-18.33|alu.v:14.5-46.12" *)  _0005_[1];
  assign _0005_[1] = \U_COUNTER.count [2] |(* src = "alu.v:17.33-17.33|alu.v:14.5-46.12" *)  \U_COUNTER.count [3];
  assign _0058_ = _0002_[0] |(* src = "alu.v:17.33-17.33|alu.v:14.5-46.12" *)  _0005_[1];
  assign _0006_[0] = _0229_[0] |(* src = "alu.v:39.28-39.34" *)  _0229_[1];
  assign _0006_[1] = _0229_[2] |(* src = "alu.v:39.28-39.34" *)  _0229_[3];
  assign _0006_[2] = _0229_[4] |(* src = "alu.v:39.28-39.34" *)  _0229_[5];
  assign _0006_[3] = _0229_[6] |(* src = "alu.v:39.28-39.34" *)  _0229_[7];
  assign _0007_[0] = _0006_[0] |(* src = "alu.v:39.28-39.34" *)  _0006_[1];
  assign _0007_[1] = _0006_[2] |(* src = "alu.v:39.28-39.34" *)  _0006_[3];
  assign _0059_ = _0007_[0] |(* src = "alu.v:39.28-39.34" *)  _0007_[1];
  assign _0060_ = _0001_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0000_[1];
  assign _0008_ = _0003_[0] |(* src = "alu.v:14.17-14.17|alu.v:14.5-46.12" *)  _0005_[1];
  assign _0009_[0] = _0174_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0175_;
  assign _0009_[1] = _0176_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0177_;
  assign _0009_[2] = _0178_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0179_;
  assign _0009_[3] = _0180_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0181_;
  assign _0009_[4] = _0182_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0183_;
  assign _0009_[5] = _0184_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0185_;
  assign _0009_[6] = _0186_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0187_;
  assign _0009_[7] = _0188_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0189_;
  assign _0010_[0] = _0009_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0009_[1];
  assign _0010_[1] = _0009_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0009_[3];
  assign _0010_[2] = _0009_[4] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0009_[5];
  assign _0010_[3] = _0009_[6] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0009_[7];
  assign _0011_[0] = _0010_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0010_[1];
  assign _0011_[1] = _0010_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0010_[3];
  assign _0012_ = _0011_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0011_[1];
  assign _0013_[1] = _0061_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0062_;
  assign _0013_[2] = _0063_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0064_;
  assign _0013_[4] = _0065_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0066_;
  assign _0013_[5] = _0067_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0068_;
  assign _0013_[6] = _0069_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0070_;
  assign _0013_[7] = _0071_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0072_;
  assign _0014_[0] = _0013_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0013_[1];
  assign _0014_[1] = _0013_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0013_[3];
  assign _0014_[2] = _0013_[4] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0013_[5];
  assign _0014_[3] = _0013_[6] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0013_[7];
  assign _0015_[0] = _0014_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0014_[1];
  assign _0015_[1] = _0014_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0014_[3];
  assign _0016_ = _0015_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0015_[1];
  assign _0017_[1] = _0073_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0074_;
  assign _0017_[2] = _0075_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0076_;
  assign _0017_[3] = _0077_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0078_;
  assign _0017_[4] = _0079_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0080_;
  assign _0017_[5] = _0081_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0082_;
  assign _0017_[6] = _0083_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0084_;
  assign _0017_[7] = _0085_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0086_;
  assign _0018_[1] = _0017_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0017_[3];
  assign _0018_[2] = _0017_[4] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0017_[5];
  assign _0018_[3] = _0017_[6] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0017_[7];
  assign _0019_[0] = _0017_[1] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0018_[1];
  assign _0019_[1] = _0018_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0018_[3];
  assign _0020_ = _0019_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0019_[1];
  assign _0021_[1] = _0087_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0088_;
  assign _0021_[2] = _0089_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0090_;
  assign _0021_[3] = _0091_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0092_;
  assign _0021_[4] = _0093_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0094_;
  assign _0021_[5] = _0095_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0096_;
  assign _0021_[6] = _0097_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0098_;
  assign _0021_[7] = _0099_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0100_;
  assign _0022_[1] = _0021_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0021_[3];
  assign _0022_[2] = _0021_[4] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0021_[5];
  assign _0022_[3] = _0021_[6] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0021_[7];
  assign _0023_[0] = _0021_[1] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0022_[1];
  assign _0023_[1] = _0022_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0022_[3];
  assign _0024_ = _0023_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0023_[1];
  assign _0025_[1] = _0101_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0102_;
  assign _0025_[2] = _0103_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0104_;
  assign _0025_[3] = _0105_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0106_;
  assign _0025_[4] = _0107_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0108_;
  assign _0025_[5] = _0109_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0110_;
  assign _0025_[6] = _0111_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0112_;
  assign _0025_[7] = _0113_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0114_;
  assign _0026_[1] = _0025_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0025_[3];
  assign _0026_[2] = _0025_[4] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0025_[5];
  assign _0026_[3] = _0025_[6] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0025_[7];
  assign _0027_[0] = _0025_[1] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0026_[1];
  assign _0027_[1] = _0026_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0026_[3];
  assign _0028_ = _0027_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0027_[1];
  assign _0029_[1] = _0115_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0116_;
  assign _0029_[2] = _0117_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0118_;
  assign _0029_[3] = _0119_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0120_;
  assign _0029_[4] = _0121_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0122_;
  assign _0029_[5] = _0123_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0124_;
  assign _0029_[6] = _0125_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0126_;
  assign _0029_[7] = _0127_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0128_;
  assign _0030_[1] = _0029_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0029_[3];
  assign _0030_[2] = _0029_[4] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0029_[5];
  assign _0030_[3] = _0029_[6] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0029_[7];
  assign _0031_[0] = _0029_[1] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0030_[1];
  assign _0031_[1] = _0030_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0030_[3];
  assign _0032_ = _0031_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0031_[1];
  assign _0033_[1] = _0129_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0130_;
  assign _0033_[2] = _0131_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0132_;
  assign _0033_[3] = _0133_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0134_;
  assign _0033_[4] = _0135_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0136_;
  assign _0033_[5] = _0137_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0138_;
  assign _0033_[6] = _0139_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0140_;
  assign _0033_[7] = _0141_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0142_;
  assign _0034_[1] = _0033_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0033_[3];
  assign _0034_[2] = _0033_[4] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0033_[5];
  assign _0034_[3] = _0033_[6] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0033_[7];
  assign _0035_[0] = _0033_[1] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0034_[1];
  assign _0035_[1] = _0034_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0034_[3];
  assign _0036_ = _0035_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0035_[1];
  assign _0037_[1] = _0143_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0144_;
  assign _0037_[2] = _0145_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0146_;
  assign _0037_[3] = _0147_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0148_;
  assign _0037_[4] = _0149_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0150_;
  assign _0037_[5] = _0151_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0152_;
  assign _0037_[6] = _0153_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0154_;
  assign _0037_[7] = _0155_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0156_;
  assign _0038_[1] = _0037_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0037_[3];
  assign _0038_[2] = _0037_[4] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0037_[5];
  assign _0038_[3] = _0037_[6] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0037_[7];
  assign _0039_[0] = _0037_[1] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0038_[1];
  assign _0039_[1] = _0038_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0038_[3];
  assign _0040_ = _0039_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0039_[1];
  assign _0041_[1] = _0157_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0158_;
  assign _0041_[2] = _0159_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0160_;
  assign _0041_[4] = _0161_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0162_;
  assign _0041_[5] = _0163_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0164_;
  assign _0041_[6] = _0165_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0166_;
  assign _0041_[7] = _0167_ |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0168_;
  assign _0042_[1] = _0041_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0041_[3];
  assign _0042_[2] = _0041_[4] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0041_[5];
  assign _0042_[3] = _0041_[6] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0041_[7];
  assign _0043_[0] = _0041_[1] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0042_[1];
  assign _0043_[1] = _0042_[2] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0042_[3];
  assign _0044_ = _0043_[0] |(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0043_[1];
  assign _0175_ = ~(* src = "alu.v:36.29-36.29|alu.v:14.5-46.12" *) _0045_;
  assign _0176_ = ~(* src = "alu.v:35.29-35.29|alu.v:14.5-46.12" *) _0046_;
  assign _0177_ = ~(* src = "alu.v:34.33-34.33|alu.v:14.5-46.12" *) _0047_;
  assign _0178_ = ~(* src = "alu.v:33.33-33.33|alu.v:14.5-46.12" *) _0048_;
  assign _0179_ = ~(* src = "alu.v:30.34-30.34|alu.v:14.5-46.12" *) _0049_;
  assign _0180_ = ~(* src = "alu.v:29.34-29.34|alu.v:14.5-46.12" *) _0050_;
  assign _0181_ = ~(* src = "alu.v:26.36-26.36|alu.v:14.5-46.12" *) _0051_;
  assign _0182_ = ~(* src = "alu.v:25.36-25.36|alu.v:14.5-46.12" *) _0052_;
  assign _0183_ = ~(* src = "alu.v:24.36-24.36|alu.v:14.5-46.12" *) _0053_;
  assign _0184_ = ~(* src = "alu.v:23.33-23.33|alu.v:14.5-46.12" *) _0054_;
  assign _0185_ = ~(* src = "alu.v:22.33-22.33|alu.v:14.5-46.12" *) _0055_;
  assign _0186_ = ~(* src = "alu.v:21.33-21.33|alu.v:14.5-46.12" *) _0056_;
  assign _0187_ = ~(* src = "alu.v:18.33-18.33|alu.v:14.5-46.12" *) _0057_;
  assign _0189_ = ~(* src = "alu.v:14.17-14.17|alu.v:14.5-46.12" *) _0008_;
  assign _0188_ = ~(* src = "alu.v:17.33-17.33|alu.v:14.5-46.12" *) _0058_;
  assign _0169_[0] = ~(* src = "alu.v:39.28-39.34" *) _0059_;
  assign _0174_ = ~(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *) _0060_;
  assign _0190_[1] = up_down ? (* src = "counter.v:19.13-19.20|counter.v:19.9-22.32" *) _0245_[1] : _0248_[1];
  assign _0190_[2] = up_down ? (* src = "counter.v:19.13-19.20|counter.v:19.9-22.32" *) _0245_[2] : _0248_[2];
  assign _0190_[3] = up_down ? (* src = "counter.v:19.13-19.20|counter.v:19.9-22.32" *) _0245_[3] : _0248_[3];
  assign _0227_[0] = \U_COUNTER.count [0] ? \U_RAM.mem[15] [0] : \U_RAM.mem[14] [0];
  assign _0227_[1] = \U_COUNTER.count [0] ? \U_RAM.mem[15] [1] : \U_RAM.mem[14] [1];
  assign _0227_[2] = \U_COUNTER.count [0] ? \U_RAM.mem[15] [2] : \U_RAM.mem[14] [2];
  assign _0227_[3] = \U_COUNTER.count [0] ? \U_RAM.mem[15] [3] : \U_RAM.mem[14] [3];
  assign _0227_[4] = \U_COUNTER.count [0] ? \U_RAM.mem[15] [4] : \U_RAM.mem[14] [4];
  assign _0227_[5] = \U_COUNTER.count [0] ? \U_RAM.mem[15] [5] : \U_RAM.mem[14] [5];
  assign _0227_[6] = \U_COUNTER.count [0] ? \U_RAM.mem[15] [6] : \U_RAM.mem[14] [6];
  assign _0227_[7] = \U_COUNTER.count [0] ? \U_RAM.mem[15] [7] : \U_RAM.mem[14] [7];
  assign _0226_[0] = \U_COUNTER.count [0] ? \U_RAM.mem[13] [0] : \U_RAM.mem[12] [0];
  assign _0226_[1] = \U_COUNTER.count [0] ? \U_RAM.mem[13] [1] : \U_RAM.mem[12] [1];
  assign _0226_[2] = \U_COUNTER.count [0] ? \U_RAM.mem[13] [2] : \U_RAM.mem[12] [2];
  assign _0226_[3] = \U_COUNTER.count [0] ? \U_RAM.mem[13] [3] : \U_RAM.mem[12] [3];
  assign _0226_[4] = \U_COUNTER.count [0] ? \U_RAM.mem[13] [4] : \U_RAM.mem[12] [4];
  assign _0226_[5] = \U_COUNTER.count [0] ? \U_RAM.mem[13] [5] : \U_RAM.mem[12] [5];
  assign _0226_[6] = \U_COUNTER.count [0] ? \U_RAM.mem[13] [6] : \U_RAM.mem[12] [6];
  assign _0226_[7] = \U_COUNTER.count [0] ? \U_RAM.mem[13] [7] : \U_RAM.mem[12] [7];
  assign _0225_[0] = \U_COUNTER.count [0] ? \U_RAM.mem[11] [0] : \U_RAM.mem[10] [0];
  assign _0225_[1] = \U_COUNTER.count [0] ? \U_RAM.mem[11] [1] : \U_RAM.mem[10] [1];
  assign _0225_[2] = \U_COUNTER.count [0] ? \U_RAM.mem[11] [2] : \U_RAM.mem[10] [2];
  assign _0225_[3] = \U_COUNTER.count [0] ? \U_RAM.mem[11] [3] : \U_RAM.mem[10] [3];
  assign _0225_[4] = \U_COUNTER.count [0] ? \U_RAM.mem[11] [4] : \U_RAM.mem[10] [4];
  assign _0225_[5] = \U_COUNTER.count [0] ? \U_RAM.mem[11] [5] : \U_RAM.mem[10] [5];
  assign _0225_[6] = \U_COUNTER.count [0] ? \U_RAM.mem[11] [6] : \U_RAM.mem[10] [6];
  assign _0225_[7] = \U_COUNTER.count [0] ? \U_RAM.mem[11] [7] : \U_RAM.mem[10] [7];
  assign _0224_[0] = \U_COUNTER.count [0] ? \U_RAM.mem[9] [0] : \U_RAM.mem[8] [0];
  assign _0224_[1] = \U_COUNTER.count [0] ? \U_RAM.mem[9] [1] : \U_RAM.mem[8] [1];
  assign _0224_[2] = \U_COUNTER.count [0] ? \U_RAM.mem[9] [2] : \U_RAM.mem[8] [2];
  assign _0224_[3] = \U_COUNTER.count [0] ? \U_RAM.mem[9] [3] : \U_RAM.mem[8] [3];
  assign _0224_[4] = \U_COUNTER.count [0] ? \U_RAM.mem[9] [4] : \U_RAM.mem[8] [4];
  assign _0224_[5] = \U_COUNTER.count [0] ? \U_RAM.mem[9] [5] : \U_RAM.mem[8] [5];
  assign _0224_[6] = \U_COUNTER.count [0] ? \U_RAM.mem[9] [6] : \U_RAM.mem[8] [6];
  assign _0224_[7] = \U_COUNTER.count [0] ? \U_RAM.mem[9] [7] : \U_RAM.mem[8] [7];
  assign _0223_[0] = \U_COUNTER.count [0] ? \U_RAM.mem[7] [0] : \U_RAM.mem[6] [0];
  assign _0223_[1] = \U_COUNTER.count [0] ? \U_RAM.mem[7] [1] : \U_RAM.mem[6] [1];
  assign _0223_[2] = \U_COUNTER.count [0] ? \U_RAM.mem[7] [2] : \U_RAM.mem[6] [2];
  assign _0223_[3] = \U_COUNTER.count [0] ? \U_RAM.mem[7] [3] : \U_RAM.mem[6] [3];
  assign _0223_[4] = \U_COUNTER.count [0] ? \U_RAM.mem[7] [4] : \U_RAM.mem[6] [4];
  assign _0223_[5] = \U_COUNTER.count [0] ? \U_RAM.mem[7] [5] : \U_RAM.mem[6] [5];
  assign _0223_[6] = \U_COUNTER.count [0] ? \U_RAM.mem[7] [6] : \U_RAM.mem[6] [6];
  assign _0223_[7] = \U_COUNTER.count [0] ? \U_RAM.mem[7] [7] : \U_RAM.mem[6] [7];
  assign _0222_[0] = \U_COUNTER.count [0] ? \U_RAM.mem[5] [0] : \U_RAM.mem[4] [0];
  assign _0222_[1] = \U_COUNTER.count [0] ? \U_RAM.mem[5] [1] : \U_RAM.mem[4] [1];
  assign _0222_[2] = \U_COUNTER.count [0] ? \U_RAM.mem[5] [2] : \U_RAM.mem[4] [2];
  assign _0222_[3] = \U_COUNTER.count [0] ? \U_RAM.mem[5] [3] : \U_RAM.mem[4] [3];
  assign _0222_[4] = \U_COUNTER.count [0] ? \U_RAM.mem[5] [4] : \U_RAM.mem[4] [4];
  assign _0222_[5] = \U_COUNTER.count [0] ? \U_RAM.mem[5] [5] : \U_RAM.mem[4] [5];
  assign _0222_[6] = \U_COUNTER.count [0] ? \U_RAM.mem[5] [6] : \U_RAM.mem[4] [6];
  assign _0222_[7] = \U_COUNTER.count [0] ? \U_RAM.mem[5] [7] : \U_RAM.mem[4] [7];
  assign _0221_[0] = \U_COUNTER.count [0] ? \U_RAM.mem[3] [0] : \U_RAM.mem[2] [0];
  assign _0221_[1] = \U_COUNTER.count [0] ? \U_RAM.mem[3] [1] : \U_RAM.mem[2] [1];
  assign _0221_[2] = \U_COUNTER.count [0] ? \U_RAM.mem[3] [2] : \U_RAM.mem[2] [2];
  assign _0221_[3] = \U_COUNTER.count [0] ? \U_RAM.mem[3] [3] : \U_RAM.mem[2] [3];
  assign _0221_[4] = \U_COUNTER.count [0] ? \U_RAM.mem[3] [4] : \U_RAM.mem[2] [4];
  assign _0221_[5] = \U_COUNTER.count [0] ? \U_RAM.mem[3] [5] : \U_RAM.mem[2] [5];
  assign _0221_[6] = \U_COUNTER.count [0] ? \U_RAM.mem[3] [6] : \U_RAM.mem[2] [6];
  assign _0221_[7] = \U_COUNTER.count [0] ? \U_RAM.mem[3] [7] : \U_RAM.mem[2] [7];
  assign _0220_[0] = \U_COUNTER.count [0] ? \U_RAM.mem[1] [0] : \U_RAM.mem[0] [0];
  assign _0220_[1] = \U_COUNTER.count [0] ? \U_RAM.mem[1] [1] : \U_RAM.mem[0] [1];
  assign _0220_[2] = \U_COUNTER.count [0] ? \U_RAM.mem[1] [2] : \U_RAM.mem[0] [2];
  assign _0220_[3] = \U_COUNTER.count [0] ? \U_RAM.mem[1] [3] : \U_RAM.mem[0] [3];
  assign _0220_[4] = \U_COUNTER.count [0] ? \U_RAM.mem[1] [4] : \U_RAM.mem[0] [4];
  assign _0220_[5] = \U_COUNTER.count [0] ? \U_RAM.mem[1] [5] : \U_RAM.mem[0] [5];
  assign _0220_[6] = \U_COUNTER.count [0] ? \U_RAM.mem[1] [6] : \U_RAM.mem[0] [6];
  assign _0220_[7] = \U_COUNTER.count [0] ? \U_RAM.mem[1] [7] : \U_RAM.mem[0] [7];
  assign _0219_[0] = \U_COUNTER.count [1] ? _0227_[0] : _0226_[0];
  assign _0219_[1] = \U_COUNTER.count [1] ? _0227_[1] : _0226_[1];
  assign _0219_[2] = \U_COUNTER.count [1] ? _0227_[2] : _0226_[2];
  assign _0219_[3] = \U_COUNTER.count [1] ? _0227_[3] : _0226_[3];
  assign _0219_[4] = \U_COUNTER.count [1] ? _0227_[4] : _0226_[4];
  assign _0219_[5] = \U_COUNTER.count [1] ? _0227_[5] : _0226_[5];
  assign _0219_[6] = \U_COUNTER.count [1] ? _0227_[6] : _0226_[6];
  assign _0219_[7] = \U_COUNTER.count [1] ? _0227_[7] : _0226_[7];
  assign _0218_[0] = \U_COUNTER.count [1] ? _0225_[0] : _0224_[0];
  assign _0218_[1] = \U_COUNTER.count [1] ? _0225_[1] : _0224_[1];
  assign _0218_[2] = \U_COUNTER.count [1] ? _0225_[2] : _0224_[2];
  assign _0218_[3] = \U_COUNTER.count [1] ? _0225_[3] : _0224_[3];
  assign _0218_[4] = \U_COUNTER.count [1] ? _0225_[4] : _0224_[4];
  assign _0218_[5] = \U_COUNTER.count [1] ? _0225_[5] : _0224_[5];
  assign _0218_[6] = \U_COUNTER.count [1] ? _0225_[6] : _0224_[6];
  assign _0218_[7] = \U_COUNTER.count [1] ? _0225_[7] : _0224_[7];
  assign _0217_[0] = \U_COUNTER.count [1] ? _0223_[0] : _0222_[0];
  assign _0217_[1] = \U_COUNTER.count [1] ? _0223_[1] : _0222_[1];
  assign _0217_[2] = \U_COUNTER.count [1] ? _0223_[2] : _0222_[2];
  assign _0217_[3] = \U_COUNTER.count [1] ? _0223_[3] : _0222_[3];
  assign _0217_[4] = \U_COUNTER.count [1] ? _0223_[4] : _0222_[4];
  assign _0217_[5] = \U_COUNTER.count [1] ? _0223_[5] : _0222_[5];
  assign _0217_[6] = \U_COUNTER.count [1] ? _0223_[6] : _0222_[6];
  assign _0217_[7] = \U_COUNTER.count [1] ? _0223_[7] : _0222_[7];
  assign _0216_[0] = \U_COUNTER.count [1] ? _0221_[0] : _0220_[0];
  assign _0216_[1] = \U_COUNTER.count [1] ? _0221_[1] : _0220_[1];
  assign _0216_[2] = \U_COUNTER.count [1] ? _0221_[2] : _0220_[2];
  assign _0216_[3] = \U_COUNTER.count [1] ? _0221_[3] : _0220_[3];
  assign _0216_[4] = \U_COUNTER.count [1] ? _0221_[4] : _0220_[4];
  assign _0216_[5] = \U_COUNTER.count [1] ? _0221_[5] : _0220_[5];
  assign _0216_[6] = \U_COUNTER.count [1] ? _0221_[6] : _0220_[6];
  assign _0216_[7] = \U_COUNTER.count [1] ? _0221_[7] : _0220_[7];
  assign _0215_[0] = \U_COUNTER.count [2] ? _0219_[0] : _0218_[0];
  assign _0215_[1] = \U_COUNTER.count [2] ? _0219_[1] : _0218_[1];
  assign _0215_[2] = \U_COUNTER.count [2] ? _0219_[2] : _0218_[2];
  assign _0215_[3] = \U_COUNTER.count [2] ? _0219_[3] : _0218_[3];
  assign _0215_[4] = \U_COUNTER.count [2] ? _0219_[4] : _0218_[4];
  assign _0215_[5] = \U_COUNTER.count [2] ? _0219_[5] : _0218_[5];
  assign _0215_[6] = \U_COUNTER.count [2] ? _0219_[6] : _0218_[6];
  assign _0215_[7] = \U_COUNTER.count [2] ? _0219_[7] : _0218_[7];
  assign _0214_[0] = \U_COUNTER.count [2] ? _0217_[0] : _0216_[0];
  assign _0214_[1] = \U_COUNTER.count [2] ? _0217_[1] : _0216_[1];
  assign _0214_[2] = \U_COUNTER.count [2] ? _0217_[2] : _0216_[2];
  assign _0214_[3] = \U_COUNTER.count [2] ? _0217_[3] : _0216_[3];
  assign _0214_[4] = \U_COUNTER.count [2] ? _0217_[4] : _0216_[4];
  assign _0214_[5] = \U_COUNTER.count [2] ? _0217_[5] : _0216_[5];
  assign _0214_[6] = \U_COUNTER.count [2] ? _0217_[6] : _0216_[6];
  assign _0214_[7] = \U_COUNTER.count [2] ? _0217_[7] : _0216_[7];
  assign _0191_[0] = \U_COUNTER.count [3] ? _0215_[0] : _0214_[0];
  assign _0191_[1] = \U_COUNTER.count [3] ? _0215_[1] : _0214_[1];
  assign _0191_[2] = \U_COUNTER.count [3] ? _0215_[2] : _0214_[2];
  assign _0191_[3] = \U_COUNTER.count [3] ? _0215_[3] : _0214_[3];
  assign _0191_[4] = \U_COUNTER.count [3] ? _0215_[4] : _0214_[4];
  assign _0191_[5] = \U_COUNTER.count [3] ? _0215_[5] : _0214_[5];
  assign _0191_[6] = \U_COUNTER.count [3] ? _0215_[6] : _0214_[6];
  assign _0191_[7] = \U_COUNTER.count [3] ? _0215_[7] : _0214_[7];
  assign _0013_[0] = _0169_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0175_;
  assign _0061_ = B[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0176_;
  assign _0062_ = A[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0177_;
  assign _0063_ = _0233_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0178_;
  assign _0064_ = _0233_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0179_;
  assign _0013_[3] = A[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0180_;
  assign _0065_ = _0172_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0182_;
  assign _0066_ = _0171_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0183_;
  assign _0067_ = _0170_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0184_;
  assign _0068_ = _0229_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0185_;
  assign _0069_ = _0173_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0186_;
  assign _0070_ = _0228_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0187_;
  assign _0071_ = _0238_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0188_;
  assign _0072_ = _0229_[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0189_;
  assign _0073_ = B[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0176_;
  assign _0074_ = A[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0177_;
  assign _0075_ = _0242_[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0178_;
  assign _0076_ = _0234_[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0179_;
  assign _0077_ = A[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0180_;
  assign _0078_ = A[0] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0181_;
  assign _0079_ = _0172_[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0182_;
  assign _0080_ = _0171_[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0183_;
  assign _0081_ = _0170_[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0184_;
  assign _0082_ = _0229_[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0185_;
  assign _0083_ = _0173_[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0186_;
  assign _0084_ = _0231_[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0187_;
  assign _0085_ = _0238_[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0188_;
  assign _0086_ = _0230_[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0189_;
  assign _0087_ = B[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0176_;
  assign _0088_ = A[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0177_;
  assign _0089_ = _0242_[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0178_;
  assign _0090_ = _0234_[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0179_;
  assign _0091_ = A[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0180_;
  assign _0092_ = A[1] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0181_;
  assign _0093_ = _0172_[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0182_;
  assign _0094_ = _0171_[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0183_;
  assign _0095_ = _0170_[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0184_;
  assign _0096_ = _0229_[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0185_;
  assign _0097_ = _0173_[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0186_;
  assign _0098_ = _0231_[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0187_;
  assign _0099_ = _0238_[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0188_;
  assign _0100_ = _0230_[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0189_;
  assign _0101_ = B[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0176_;
  assign _0102_ = A[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0177_;
  assign _0103_ = _0242_[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0178_;
  assign _0104_ = _0234_[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0179_;
  assign _0105_ = A[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0180_;
  assign _0106_ = A[2] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0181_;
  assign _0107_ = _0172_[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0182_;
  assign _0108_ = _0171_[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0183_;
  assign _0109_ = _0170_[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0184_;
  assign _0110_ = _0229_[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0185_;
  assign _0111_ = _0173_[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0186_;
  assign _0112_ = _0231_[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0187_;
  assign _0113_ = _0238_[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0188_;
  assign _0114_ = _0230_[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0189_;
  assign _0115_ = B[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0176_;
  assign _0116_ = A[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0177_;
  assign _0117_ = _0242_[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0178_;
  assign _0118_ = _0234_[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0179_;
  assign _0119_ = A[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0180_;
  assign _0120_ = A[3] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0181_;
  assign _0121_ = _0172_[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0182_;
  assign _0122_ = _0171_[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0183_;
  assign _0123_ = _0170_[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0184_;
  assign _0124_ = _0229_[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0185_;
  assign _0125_ = _0173_[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0186_;
  assign _0126_ = _0231_[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0187_;
  assign _0127_ = _0238_[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0188_;
  assign _0128_ = _0230_[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0189_;
  assign _0129_ = B[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0176_;
  assign _0130_ = A[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0177_;
  assign _0131_ = _0242_[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0178_;
  assign _0132_ = _0234_[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0179_;
  assign _0133_ = A[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0180_;
  assign _0134_ = A[4] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0181_;
  assign _0135_ = _0172_[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0182_;
  assign _0136_ = _0171_[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0183_;
  assign _0137_ = _0170_[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0184_;
  assign _0138_ = _0229_[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0185_;
  assign _0139_ = _0173_[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0186_;
  assign _0140_ = _0231_[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0187_;
  assign _0141_ = _0238_[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0188_;
  assign _0142_ = _0230_[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0189_;
  assign _0143_ = B[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0176_;
  assign _0144_ = A[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0177_;
  assign _0145_ = _0242_[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0178_;
  assign _0146_ = _0234_[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0179_;
  assign _0147_ = A[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0180_;
  assign _0148_ = A[5] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0181_;
  assign _0149_ = _0172_[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0182_;
  assign _0150_ = _0171_[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0183_;
  assign _0151_ = _0170_[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0184_;
  assign _0152_ = _0229_[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0185_;
  assign _0153_ = _0173_[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0186_;
  assign _0154_ = _0231_[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0187_;
  assign _0155_ = _0238_[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0188_;
  assign _0156_ = _0230_[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0189_;
  assign _0157_ = B[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0176_;
  assign _0158_ = A[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0177_;
  assign _0159_ = _0242_[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0178_;
  assign _0160_ = _0234_[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0179_;
  assign _0041_[3] = A[6] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0181_;
  assign _0161_ = _0172_[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0182_;
  assign _0162_ = _0171_[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0183_;
  assign _0163_ = _0170_[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0184_;
  assign _0164_ = _0229_[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0185_;
  assign _0165_ = _0173_[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0186_;
  assign _0166_ = _0231_[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0187_;
  assign _0167_ = _0238_[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0188_;
  assign _0168_ = _0230_[7] &(* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *)  _0189_;
  assign _0235_[0] = ~(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[0];
  assign _0235_[1] = ~(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[1];
  assign _0235_[2] = ~(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[2];
  assign _0235_[3] = ~(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[3];
  assign _0235_[4] = ~(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[4];
  assign _0235_[5] = ~(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[5];
  assign _0235_[6] = ~(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[6];
  assign _0235_[7] = ~(* src = "alu.v:18.27-18.32|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[7];
  assign _0170_[0] = ~(* src = "alu.v:24.27-24.35" *) _0229_[0];
  assign _0170_[1] = ~(* src = "alu.v:24.27-24.35" *) _0229_[1];
  assign _0170_[2] = ~(* src = "alu.v:24.27-24.35" *) _0229_[2];
  assign _0170_[3] = ~(* src = "alu.v:24.27-24.35" *) _0229_[3];
  assign _0170_[4] = ~(* src = "alu.v:24.27-24.35" *) _0229_[4];
  assign _0170_[5] = ~(* src = "alu.v:24.27-24.35" *) _0229_[5];
  assign _0170_[6] = ~(* src = "alu.v:24.27-24.35" *) _0229_[6];
  assign _0170_[7] = ~(* src = "alu.v:24.27-24.35" *) _0229_[7];
  assign _0171_[0] = ~(* src = "alu.v:25.27-25.35" *) _0228_[0];
  assign _0171_[1] = ~(* src = "alu.v:25.27-25.35" *) _0231_[1];
  assign _0171_[2] = ~(* src = "alu.v:25.27-25.35" *) _0231_[2];
  assign _0171_[3] = ~(* src = "alu.v:25.27-25.35" *) _0231_[3];
  assign _0171_[4] = ~(* src = "alu.v:25.27-25.35" *) _0231_[4];
  assign _0171_[5] = ~(* src = "alu.v:25.27-25.35" *) _0231_[5];
  assign _0171_[6] = ~(* src = "alu.v:25.27-25.35" *) _0231_[6];
  assign _0171_[7] = ~(* src = "alu.v:25.27-25.35" *) _0231_[7];
  assign _0172_[0] = ~(* src = "alu.v:26.27-26.35" *) _0173_[0];
  assign _0172_[1] = ~(* src = "alu.v:26.27-26.35" *) _0173_[1];
  assign _0172_[2] = ~(* src = "alu.v:26.27-26.35" *) _0173_[2];
  assign _0172_[3] = ~(* src = "alu.v:26.27-26.35" *) _0173_[3];
  assign _0172_[4] = ~(* src = "alu.v:26.27-26.35" *) _0173_[4];
  assign _0172_[5] = ~(* src = "alu.v:26.27-26.35" *) _0173_[5];
  assign _0172_[6] = ~(* src = "alu.v:26.27-26.35" *) _0173_[6];
  assign _0172_[7] = ~(* src = "alu.v:26.27-26.35" *) _0173_[7];
  assign \U_ALU.result [0] = _0012_ ? (* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *) _0016_ : 1'hx;
  assign \U_ALU.result [1] = _0012_ ? (* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *) _0020_ : 1'hx;
  assign \U_ALU.result [2] = _0012_ ? (* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *) _0024_ : 1'hx;
  assign \U_ALU.result [3] = _0012_ ? (* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *) _0028_ : 1'hx;
  assign \U_ALU.result [4] = _0012_ ? (* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *) _0032_ : 1'hx;
  assign \U_ALU.result [5] = _0012_ ? (* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *) _0036_ : 1'hx;
  assign \U_ALU.result [6] = _0012_ ? (* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *) _0040_ : 1'hx;
  assign \U_ALU.result [7] = _0012_ ? (* src = "alu.v:39.36-39.36|alu.v:14.5-46.12" *) _0044_ : 1'hx;
  assign { _0243_[31:4], _0243_[0] } = { 28'h0000000, \U_COUNTER.count [0] };
  assign _0038_[0] = _0037_[1];
  assign _0037_[0] = 1'h0;
  assign _0034_[0] = _0033_[1];
  assign _0033_[0] = 1'h0;
  assign _0030_[0] = _0029_[1];
  assign _0029_[0] = 1'h0;
  assign _0244_[31:1] = { 28'h0000000, \U_COUNTER.count [3:1] };
  assign _0026_[0] = _0025_[1];
  assign _0025_[0] = 1'h0;
  assign _0230_[0] = _0229_[0];
  assign _0022_[0] = _0021_[1];
  assign _0021_[0] = 1'h0;
  assign _0018_[0] = _0017_[1];
  assign _0017_[0] = 1'h0;
  assign { _0242_[31:9], _0242_[0] } = { _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0242_[8], _0233_[0] };
  assign _0231_[0] = _0228_[0];
  assign { _0240_[31:8], _0240_[0] } = { _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], _0240_[7], A[0] };
  assign { _0241_[31:8], _0241_[0] } = { 24'hffffff, A[0] };
  assign { _0248_[31:5], _0248_[0] } = { _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0248_[4], _0244_[0] };
  assign { _0234_[31:8], _0234_[0] } = { 23'h000000, _0232_[7], _0233_[0] };
  assign { _0232_[31:8], _0232_[0] } = { 24'h000000, A[0] };
  assign _0005_[0] = _0001_[0];
  assign { _0246_[31:4], _0246_[0] } = { _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], _0246_[3], \U_COUNTER.count [0] };
  assign _0233_[31:1] = { 24'h000000, A[7:1] };
  assign { _0247_[31:4], _0247_[0] } = { 28'hfffffff, \U_COUNTER.count [0] };
  assign _0004_[0] = _0001_[0];
  assign _0003_[1] = _0001_[1];
  assign \U_RAM.clk  = clk;
  assign \U_RAM.we  = 1'h1;
  assign \U_RAM.addr  = \U_COUNTER.count ;
  assign \U_RAM.data_in  = \U_ALU.result ;
  assign _0002_[1] = _0001_[1];
  assign { _0245_[31:4], _0245_[0] } = { 27'h0000000, _0243_[3], _0244_[0] };
  assign _0042_[0] = _0041_[1];
  assign _0041_[0] = 1'h0;
  assign \U_ALU.A  = A;
  assign \U_ALU.B  = B;
  assign \U_ALU.opcode  = \U_COUNTER.count ;
  assign _0169_[7:1] = 7'h00;
  assign \U_COUNTER.clk  = clk;
  assign \U_COUNTER.reset  = reset;
  assign \U_COUNTER.up_down  = up_down;
  assign \U_COUNTER.enable  = 1'h1;
  assign _0190_[0] = _0244_[0];
  assign ram_out = \U_RAM.data_out ;
  assign result = \U_ALU.result ;
  assign count = \U_COUNTER.count ;
endmodule
