/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* top =  1  *)
(* src = "universal_shift_register.v:3.1-42.10" *)
module universal_shift_register(clk, reset, mode, serial_left, serial_right, parallel_in, q);
  (* src = "universal_shift_register.v:4.23-4.26" *)
  input clk;
  wire clk;
  (* src = "universal_shift_register.v:5.23-5.28" *)
  input reset;
  wire reset;
  (* src = "universal_shift_register.v:6.23-6.27" *)
  input [1:0] mode;
  wire [1:0] mode;
  (* src = "universal_shift_register.v:7.23-7.34" *)
  input serial_left;
  wire serial_left;
  (* src = "universal_shift_register.v:8.23-8.35" *)
  input serial_right;
  wire serial_right;
  (* src = "universal_shift_register.v:9.23-9.34" *)
  input [3:0] parallel_in;
  wire [3:0] parallel_in;
  (* src = "universal_shift_register.v:10.23-10.24" *)
  output [3:0] q;
  reg [3:0] q;
  (* src = "universal_shift_register.v:13.1-40.4" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "universal_shift_register.v:13.1-40.4" *)
  always @(posedge clk, posedge reset)
    if (reset) q <= 4'h0;
    else if (!_04_) q <= _00_;
  function [3:0] _06_;
    input [3:0] a;
    input [11:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "universal_shift_register.v:29.45-29.45|universal_shift_register.v:17.9-38.16" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _06_ = b[3:0];
      3'b?1?:
        _06_ = b[7:4];
      3'b1??:
        _06_ = b[11:8];
      default:
        _06_ = a;
    endcase
  endfunction
  assign _00_ = _06_(4'hx, { parallel_in, q[2:0], serial_right, serial_left, q[3:1] }, { _01_, _02_, _03_ });
  assign _01_ = mode == (* full_case = 32'd1 *) (* src = "universal_shift_register.v:29.45-29.45|universal_shift_register.v:17.9-38.16" *) 2'h3;
  assign _02_ = mode == (* full_case = 32'd1 *) (* src = "universal_shift_register.v:25.44-25.44|universal_shift_register.v:17.9-38.16" *) 2'h2;
  assign _03_ = mode == (* full_case = 32'd1 *) (* src = "universal_shift_register.v:21.24-21.24|universal_shift_register.v:17.9-38.16" *) 2'h1;
  assign _04_ = ! (* full_case = 32'd1 *) (* src = "universal_shift_register.v:17.20-17.20|universal_shift_register.v:17.9-38.16" *) mode;
endmodule
