/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* top =  1  *)
(* src = "fsm.v:2.1-97.10" *)
module fsm(clk, reset, timer_done, red, yellow, green);
  (* src = "fsm.v:3.17-3.20" *)
  input clk;
  wire clk;
  (* src = "fsm.v:4.17-4.22" *)
  input reset;
  wire reset;
  (* src = "fsm.v:5.17-5.27" *)
  input timer_done;
  wire timer_done;
  (* src = "fsm.v:7.16-7.19" *)
  output red;
  wire red;
  (* src = "fsm.v:8.16-8.22" *)
  output yellow;
  wire yellow;
  (* src = "fsm.v:9.16-9.21" *)
  output green;
  wire green;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* unused_bits = "0" *)
  wire _06_;
  (* unused_bits = "0" *)
  wire _07_;
  (* unused_bits = "0" *)
  wire _08_;
  (* onehot = 32'd1 *)
  wire [2:0] current_state;
  INV_X1 _09_ (
    .A(reset),
    .ZN(_03_)
  );
  MUX2_X1 _10_ (
    .A(current_state[0]),
    .B(yellow),
    .S(timer_done),
    .Z(_00_)
  );
  MUX2_X1 _11_ (
    .A(yellow),
    .B(green),
    .S(timer_done),
    .Z(_01_)
  );
  NOR2_X1 _12_ (
    .A1(green),
    .A2(yellow),
    .ZN(red)
  );
  MUX2_X1 _13_ (
    .A(green),
    .B(current_state[0]),
    .S(timer_done),
    .Z(_02_)
  );
  INV_X1 _14_ (
    .A(reset),
    .ZN(_04_)
  );
  INV_X1 _15_ (
    .A(reset),
    .ZN(_05_)
  );
  DFFS_X1 _16_ (
    .CK(clk),
    .D(_00_),
    .Q(current_state[0]),
    .QN(_07_),
    .SN(_04_)
  );
  DFFR_X1 _17_ (
    .CK(clk),
    .D(_01_),
    .Q(yellow),
    .QN(_06_),
    .RN(_05_)
  );
  DFFR_X1 _18_ (
    .CK(clk),
    .D(_02_),
    .Q(green),
    .QN(_08_),
    .RN(_03_)
  );
  assign current_state[2:1] = { green, yellow };
endmodule
