/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* top =  1  *)
(* src = "alu.v:3.1-83.10" *)
module alu(A, B, opcode, Result, Carry, Overflow, Zero, Negative);
  (* src = "alu.v:4.18-4.19" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "alu.v:5.18-5.19" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "alu.v:6.18-6.24" *)
  input [2:0] opcode;
  wire [2:0] opcode;
  (* src = "alu.v:8.22-8.28" *)
  output [3:0] Result;
  wire [3:0] Result;
  (* src = "alu.v:9.16-9.21" *)
  output Carry;
  wire Carry;
  (* src = "alu.v:10.16-10.24" *)
  output Overflow;
  wire Overflow;
  (* src = "alu.v:11.12-11.16" *)
  output Zero;
  wire Zero;
  (* src = "alu.v:12.12-12.20" *)
  output Negative;
  wire Negative;
  (* src = "alu.v:30.20-30.25" *)
  wire [4:0] _00_;
  (* src = "alu.v:35.18-35.31" *)
  wire _01_;
  (* src = "alu.v:35.18-35.43" *)
  wire _02_;
  (* src = "alu.v:36.19-36.31" *)
  wire _03_;
  (* src = "alu.v:36.19-36.44" *)
  wire _04_;
  (* src = "alu.v:47.18-47.30" *)
  wire _05_;
  (* src = "alu.v:47.18-47.42" *)
  wire _06_;
  (* src = "alu.v:48.19-48.31" *)
  wire _07_;
  (* src = "alu.v:48.19-48.44" *)
  wire _08_;
  (* src = "alu.v:53.22-53.27" *)
  wire [3:0] _09_;
  wire _10_;
  (* src = "alu.v:35.18-35.23" *)
  wire _11_;
  (* src = "alu.v:35.26-35.31" *)
  wire _12_;
  (* src = "alu.v:36.34-36.44" *)
  wire _13_;
  (* src = "alu.v:48.34-48.44" *)
  wire _14_;
  (* src = "alu.v:65.22-65.24" *)
  wire [3:0] _15_;
  (* src = "alu.v:35.17-36.45" *)
  wire _16_;
  (* src = "alu.v:47.17-48.45" *)
  wire _17_;
  (* src = "alu.v:57.22-57.27" *)
  wire [3:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  (* src = "alu.v:42.20-42.25" *)
  wire [4:0] _27_;
  (* src = "alu.v:61.22-61.27" *)
  wire [3:0] _28_;
  assign _00_ = A + (* src = "alu.v:30.20-30.25" *) B;
  assign _01_ = _11_ & (* src = "alu.v:35.18-35.31" *) _12_;
  assign _02_ = _01_ & (* src = "alu.v:35.18-35.43" *) _00_[3];
  assign _03_ = A[3] & (* src = "alu.v:36.19-36.31" *) B[3];
  assign _04_ = _03_ & (* src = "alu.v:36.19-36.44" *) _13_;
  assign _05_ = _11_ & (* src = "alu.v:47.18-47.30" *) B[3];
  assign _06_ = _05_ & (* src = "alu.v:47.18-47.42" *) _27_[3];
  assign _07_ = A[3] & (* src = "alu.v:48.19-48.31" *) _12_;
  assign _08_ = _07_ & (* src = "alu.v:48.19-48.44" *) _14_;
  assign _09_ = A & (* src = "alu.v:53.22-53.27" *) B;
  assign _10_ = | { _24_, _23_, _22_, _21_, _20_, _19_ };
  assign Zero = ! (* src = "alu.v:79.16-79.33" *) Result;
  assign _13_ = ~ (* src = "alu.v:36.34-36.44" *) _00_[3];
  assign _11_ = ~ (* src = "alu.v:47.18-47.23" *) A[3];
  assign _12_ = ~ (* src = "alu.v:48.26-48.31" *) B[3];
  assign _14_ = ~ (* src = "alu.v:48.34-48.44" *) _27_[3];
  assign _15_ = ~ (* src = "alu.v:65.22-65.24" *) A;
  assign _16_ = _02_ | (* src = "alu.v:35.17-36.45" *) _04_;
  assign _17_ = _06_ | (* src = "alu.v:47.17-48.45" *) _08_;
  assign _18_ = A | (* src = "alu.v:57.22-57.27" *) B;
  function [0:0] _49_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "alu.v:69.29-69.29|alu.v:25.5-75.12" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _49_ = b[0:0];
      3'b?1?:
        _49_ = b[1:1];
      3'b1??:
        _49_ = b[2:2];
      default:
        _49_ = a;
    endcase
  endfunction
  assign Overflow = _49_(1'hx, { 1'h0, _17_, _16_ }, { _10_, _25_, _26_ });
  function [0:0] _50_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "alu.v:69.29-69.29|alu.v:25.5-75.12" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _50_ = b[0:0];
      3'b?1?:
        _50_ = b[1:1];
      3'b1??:
        _50_ = b[2:2];
      default:
        _50_ = a;
    endcase
  endfunction
  assign Carry = _50_(1'hx, { 1'h0, _27_[4], _00_[4] }, { _10_, _25_, _26_ });
  function [3:0] _51_;
    input [3:0] a;
    input [31:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "alu.v:69.29-69.29|alu.v:25.5-75.12" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _51_ = b[3:0];
      8'b??????1?:
        _51_ = b[7:4];
      8'b?????1??:
        _51_ = b[11:8];
      8'b????1???:
        _51_ = b[15:12];
      8'b???1????:
        _51_ = b[19:16];
      8'b??1?????:
        _51_ = b[23:20];
      8'b?1??????:
        _51_ = b[27:24];
      8'b1???????:
        _51_ = b[31:28];
      default:
        _51_ = a;
    endcase
  endfunction
  assign Result = _51_(4'hx, { _00_[3:0], _27_[3:0], _09_, _18_, _28_, _15_, A[2:0], 2'h0, A[3:1] }, { _26_, _25_, _24_, _23_, _22_, _21_, _20_, _19_ });
  assign _25_ = opcode == (* full_case = 32'd1 *) (* src = "alu.v:37.12-37.12|alu.v:25.5-75.12" *) 3'h1;
  assign _26_ = ! (* full_case = 32'd1 *) (* src = "alu.v:25.17-25.17|alu.v:25.5-75.12" *) opcode;
  assign _19_ = opcode == (* full_case = 32'd1 *) (* src = "alu.v:69.29-69.29|alu.v:25.5-75.12" *) 3'h7;
  assign _20_ = opcode == (* full_case = 32'd1 *) (* src = "alu.v:65.25-65.25|alu.v:25.5-75.12" *) 3'h6;
  assign _21_ = opcode == (* full_case = 32'd1 *) (* src = "alu.v:61.28-61.28|alu.v:25.5-75.12" *) 3'h5;
  assign _22_ = opcode == (* full_case = 32'd1 *) (* src = "alu.v:57.28-57.28|alu.v:25.5-75.12" *) 3'h4;
  assign _23_ = opcode == (* full_case = 32'd1 *) (* src = "alu.v:53.28-53.28|alu.v:25.5-75.12" *) 3'h3;
  assign _24_ = opcode == (* full_case = 32'd1 *) (* src = "alu.v:49.12-49.12|alu.v:25.5-75.12" *) 3'h2;
  assign _27_ = A - (* src = "alu.v:42.20-42.25" *) B;
  assign _28_ = A ^ (* src = "alu.v:61.22-61.27" *) B;
  assign Negative = Result[3];
endmodule
