/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* top =  1  *)
(* src = "lfsr_4bit.v:3.1-16.10" *)
module lfsr_4bit(clk, reset, q);
  (* src = "lfsr_4bit.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "lfsr_4bit.v:5.17-5.22" *)
  input reset;
  wire reset;
  (* src = "lfsr_4bit.v:6.23-6.24" *)
  output [3:0] q;
  reg [3:0] q;
  (* src = "lfsr_4bit.v:9.1-14.4" *)
  wire [3:0] _0_;
  (* src = "lfsr_4bit.v:9.1-14.4" *)
  always @(posedge clk, posedge reset)
    if (reset) q[0] <= 1'h1;
    else q[0] <= _0_[0];
  (* src = "lfsr_4bit.v:9.1-14.4" *)
  always @(posedge clk, posedge reset)
    if (reset) q[1] <= 1'h0;
    else q[1] <= q[0];
  (* src = "lfsr_4bit.v:9.1-14.4" *)
  always @(posedge clk, posedge reset)
    if (reset) q[2] <= 1'h0;
    else q[2] <= q[1];
  (* src = "lfsr_4bit.v:9.1-14.4" *)
  always @(posedge clk, posedge reset)
    if (reset) q[3] <= 1'h0;
    else q[3] <= q[2];
  assign _0_[0] = q[3] ^(* src = "lfsr_4bit.v:13.23-13.34" *)  q[2];
  assign _0_[3:1] = q[2:0];
endmodule
